USE [HOC_Kashikiri]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [NonClusteredIndex-20201030-082007]    Script Date: 10/30/2020 10:03:42 AM ******/
CREATE UNIQUE NONCLUSTERED INDEX [NonClusteredIndex-20201030-082007] ON [dbo].[TKD_Yyksho]
(
	[UkeNo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO