Use HOC_Kashikiri
ALTER TABLE TKD_Coupon ADD TenantCdSeq INT NOT NULL DEFAULT 1 WITH VALUES;
ALTER TABLE TKD_NyShmi ADD TenantCdSeq INT NOT NULL DEFAULT 1 WITH VALUES;
ALTER TABLE TKD_NyuSih ADD TenantCdSeq INT NOT NULL DEFAULT 1 WITH VALUES;
ALTER TABLE TKD_NyShCu ADD TenantCdSeq INT NOT NULL DEFAULT 1 WITH VALUES;