USE [HOC_Kashikiri]
GO

SET ANSI_PADDING ON
GO
BEGIN TRANSACTION;

--ALTER TABLE [dbo].[TKD_EtcImport] DROP CONSTRAINT [DEFAULT_VAL] WITH ( ONLINE = OFF )

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='TKD_EtcImport1'  )
BEGIN
	ALTER TABLE [dbo].[TKD_EtcImport] DROP CONSTRAINT [TKD_EtcImport1] WITH ( ONLINE = OFF )
END

--IF COL_LENGTH('TKD_EtcImport','TenantCdSeq') IS NOT NULL
--BEGIN
--	ALTER TABLE [dbo].[TKD_EtcImport]
--	DROP COLUMN TenantCdSeq;
--END

ALTER TABLE [dbo].[TKD_EtcImport] ADD TenantCdSeq INT NOT NULL CONSTRAINT DEFAULT_VAL DEFAULT 1;

/****** Object:  Index [TKD_EtcImport1]    Script Date: 5/4/2021 10:34:13 AM ******/
ALTER TABLE [dbo].[TKD_EtcImport] ADD  CONSTRAINT [TKD_EtcImport1] PRIMARY KEY CLUSTERED 
(
    [FileName] ASC,
    [CardNo] ASC,
    [EtcRen] ASC,
    [TenantCdSeq] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
COMMIT;

