//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HassyaAllrightCloud.Reports.ReportTemplate.BusTypeList {
    
    public partial class BusTypeListB4 : DevExpress.XtraReports.UI.XtraReport {
        private void InitializeComponent() {
            DevExpress.XtraReports.ReportInitializer reportInitializer = new DevExpress.XtraReports.ReportInitializer(this, "HassyaAllrightCloud.Reports.ReportTemplate.BusTypeList.BusTypeListB4.repx");

            // Controls
            this.TopMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.TopMarginBand>("TopMargin");
            this.BottomMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.BottomMarginBand>("BottomMargin");
            this.Detail = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("Detail");
            this.PageFooter = reportInitializer.GetControl<DevExpress.XtraReports.UI.PageFooterBand>("PageFooter");
            this.DetailReport2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailReportBand>("DetailReport2");
            this.label39 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label39");
            this.label8 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label8");
            this.label9 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label9");
            this.label10 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label10");
            this.label11 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label11");
            this.label12 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label12");
            this.label7 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label7");
            this.label6 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label6");
            this.Detail3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("Detail3");
            this.ReportHeader2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportHeaderBand>("ReportHeader2");
            this.table6 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table6");
            this.tableRow6 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow6");
            this.tableCell166 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell166");
            this.tableCell168 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell168");
            this.tableCell169 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell169");
            this.tableCell170 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell170");
            this.tableCell171 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell171");
            this.tableCell172 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell172");
            this.tableCell173 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell173");
            this.tableCell174 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell174");
            this.tableCell175 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell175");
            this.tableCell176 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell176");
            this.tableCell177 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell177");
            this.tableCell178 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell178");
            this.tableCell179 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell179");
            this.tableCell180 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell180");
            this.tableCell181 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell181");
            this.tableCell182 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell182");
            this.tableCell183 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell183");
            this.tableCell184 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell184");
            this.tableCell185 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell185");
            this.tableCell186 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell186");
            this.tableCell187 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell187");
            this.tableCell188 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell188");
            this.tableCell189 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell189");
            this.tableCell190 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell190");
            this.tableCell191 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell191");
            this.tableCell192 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell192");
            this.tableCell193 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell193");
            this.tableCell194 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell194");
            this.tableCell195 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell195");
            this.tableCell196 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell196");
            this.tableCell197 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell197");
            this.tableCell198 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell198");
            this.tableCell1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell1");
            this.table5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table5");
            this.tableRow5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow5");
            this.tableCell133 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell133");
            this.tableCell135 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell135");
            this.tableCell136 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell136");
            this.tableCell137 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell137");
            this.tableCell138 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell138");
            this.tableCell139 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell139");
            this.tableCell140 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell140");
            this.tableCell141 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell141");
            this.tableCell142 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell142");
            this.tableCell143 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell143");
            this.tableCell144 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell144");
            this.tableCell145 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell145");
            this.tableCell146 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell146");
            this.tableCell147 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell147");
            this.tableCell148 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell148");
            this.tableCell149 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell149");
            this.tableCell150 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell150");
            this.tableCell151 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell151");
            this.tableCell152 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell152");
            this.tableCell153 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell153");
            this.tableCell154 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell154");
            this.tableCell155 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell155");
            this.tableCell156 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell156");
            this.tableCell157 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell157");
            this.tableCell158 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell158");
            this.tableCell159 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell159");
            this.tableCell160 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell160");
            this.tableCell161 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell161");
            this.tableCell162 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell162");
            this.tableCell163 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell163");
            this.tableCell164 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell164");
            this.tableCell165 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell165");
            this.tableCell2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell2");

            // Data Sources
            this.objectDataSource1 = reportInitializer.GetDataSource<DevExpress.DataAccess.ObjectBinding.ObjectDataSource>("objectDataSource1");
        }
        private DevExpress.XtraReports.UI.TopMarginBand TopMargin;
        private DevExpress.XtraReports.UI.BottomMarginBand BottomMargin;
        private DevExpress.XtraReports.UI.DetailBand Detail;
        private DevExpress.XtraReports.UI.PageFooterBand PageFooter;
        private DevExpress.XtraReports.UI.DetailReportBand DetailReport2;
        private DevExpress.XtraReports.UI.XRLabel label39;
        private DevExpress.XtraReports.UI.XRLabel label8;
        private DevExpress.XtraReports.UI.XRLabel label9;
        private DevExpress.XtraReports.UI.XRLabel label10;
        private DevExpress.XtraReports.UI.XRLabel label11;
        private DevExpress.XtraReports.UI.XRLabel label12;
        private DevExpress.XtraReports.UI.XRLabel label7;
        private DevExpress.XtraReports.UI.XRLabel label6;
        private DevExpress.XtraReports.UI.DetailBand Detail3;
        private DevExpress.XtraReports.UI.ReportHeaderBand ReportHeader2;
        private DevExpress.XtraReports.UI.XRTable table6;
        private DevExpress.XtraReports.UI.XRTableRow tableRow6;
        private DevExpress.XtraReports.UI.XRTableCell tableCell166;
        private DevExpress.XtraReports.UI.XRTableCell tableCell168;
        private DevExpress.XtraReports.UI.XRTableCell tableCell169;
        private DevExpress.XtraReports.UI.XRTableCell tableCell170;
        private DevExpress.XtraReports.UI.XRTableCell tableCell171;
        private DevExpress.XtraReports.UI.XRTableCell tableCell172;
        private DevExpress.XtraReports.UI.XRTableCell tableCell173;
        private DevExpress.XtraReports.UI.XRTableCell tableCell174;
        private DevExpress.XtraReports.UI.XRTableCell tableCell175;
        private DevExpress.XtraReports.UI.XRTableCell tableCell176;
        private DevExpress.XtraReports.UI.XRTableCell tableCell177;
        private DevExpress.XtraReports.UI.XRTableCell tableCell178;
        private DevExpress.XtraReports.UI.XRTableCell tableCell179;
        private DevExpress.XtraReports.UI.XRTableCell tableCell180;
        private DevExpress.XtraReports.UI.XRTableCell tableCell181;
        private DevExpress.XtraReports.UI.XRTableCell tableCell182;
        private DevExpress.XtraReports.UI.XRTableCell tableCell183;
        private DevExpress.XtraReports.UI.XRTableCell tableCell184;
        private DevExpress.XtraReports.UI.XRTableCell tableCell185;
        private DevExpress.XtraReports.UI.XRTableCell tableCell186;
        private DevExpress.XtraReports.UI.XRTableCell tableCell187;
        private DevExpress.XtraReports.UI.XRTableCell tableCell188;
        private DevExpress.XtraReports.UI.XRTableCell tableCell189;
        private DevExpress.XtraReports.UI.XRTableCell tableCell190;
        private DevExpress.XtraReports.UI.XRTableCell tableCell191;
        private DevExpress.XtraReports.UI.XRTableCell tableCell192;
        private DevExpress.XtraReports.UI.XRTableCell tableCell193;
        private DevExpress.XtraReports.UI.XRTableCell tableCell194;
        private DevExpress.XtraReports.UI.XRTableCell tableCell195;
        private DevExpress.XtraReports.UI.XRTableCell tableCell196;
        private DevExpress.XtraReports.UI.XRTableCell tableCell197;
        private DevExpress.XtraReports.UI.XRTableCell tableCell198;
        private DevExpress.XtraReports.UI.XRTableCell tableCell1;
        private DevExpress.XtraReports.UI.XRTable table5;
        private DevExpress.XtraReports.UI.XRTableRow tableRow5;
        private DevExpress.XtraReports.UI.XRTableCell tableCell133;
        private DevExpress.XtraReports.UI.XRTableCell tableCell135;
        private DevExpress.XtraReports.UI.XRTableCell tableCell136;
        private DevExpress.XtraReports.UI.XRTableCell tableCell137;
        private DevExpress.XtraReports.UI.XRTableCell tableCell138;
        private DevExpress.XtraReports.UI.XRTableCell tableCell139;
        private DevExpress.XtraReports.UI.XRTableCell tableCell140;
        private DevExpress.XtraReports.UI.XRTableCell tableCell141;
        private DevExpress.XtraReports.UI.XRTableCell tableCell142;
        private DevExpress.XtraReports.UI.XRTableCell tableCell143;
        private DevExpress.XtraReports.UI.XRTableCell tableCell144;
        private DevExpress.XtraReports.UI.XRTableCell tableCell145;
        private DevExpress.XtraReports.UI.XRTableCell tableCell146;
        private DevExpress.XtraReports.UI.XRTableCell tableCell147;
        private DevExpress.XtraReports.UI.XRTableCell tableCell148;
        private DevExpress.XtraReports.UI.XRTableCell tableCell149;
        private DevExpress.XtraReports.UI.XRTableCell tableCell150;
        private DevExpress.XtraReports.UI.XRTableCell tableCell151;
        private DevExpress.XtraReports.UI.XRTableCell tableCell152;
        private DevExpress.XtraReports.UI.XRTableCell tableCell153;
        private DevExpress.XtraReports.UI.XRTableCell tableCell154;
        private DevExpress.XtraReports.UI.XRTableCell tableCell155;
        private DevExpress.XtraReports.UI.XRTableCell tableCell156;
        private DevExpress.XtraReports.UI.XRTableCell tableCell157;
        private DevExpress.XtraReports.UI.XRTableCell tableCell158;
        private DevExpress.XtraReports.UI.XRTableCell tableCell159;
        private DevExpress.XtraReports.UI.XRTableCell tableCell160;
        private DevExpress.XtraReports.UI.XRTableCell tableCell161;
        private DevExpress.XtraReports.UI.XRTableCell tableCell162;
        private DevExpress.XtraReports.UI.XRTableCell tableCell163;
        private DevExpress.XtraReports.UI.XRTableCell tableCell164;
        private DevExpress.XtraReports.UI.XRTableCell tableCell165;
        private DevExpress.XtraReports.UI.XRTableCell tableCell2;
        private DevExpress.DataAccess.ObjectBinding.ObjectDataSource objectDataSource1;
    }
}
