//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HassyaAllrightCloud.Reports.ReportTemplate.BusTypeList {
    
    public partial class BusTypeListA3 : DevExpress.XtraReports.UI.XtraReport {
        private void InitializeComponent() {
            DevExpress.XtraReports.ReportInitializer reportInitializer = new DevExpress.XtraReports.ReportInitializer(this, "HassyaAllrightCloud.Reports.ReportTemplate.BusTypeList.BusTypeListA3.repx");

            // Controls
            this.TopMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.TopMarginBand>("TopMargin");
            this.BottomMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.BottomMarginBand>("BottomMargin");
            this.Detail = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("Detail");
            this.PageFooter = reportInitializer.GetControl<DevExpress.XtraReports.UI.PageFooterBand>("PageFooter");
            this.DetailReport1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailReportBand>("DetailReport1");
            this.label16 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label16");
            this.label4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label4");
            this.label2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label2");
            this.label1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label1");
            this.label3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label3");
            this.label5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label5");
            this.label6 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label6");
            this.label7 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label7");
            this.Detail2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("Detail2");
            this.ReportHeader1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportHeaderBand>("ReportHeader1");
            this.table4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table4");
            this.tableRow4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow4");
            this.tableCell100 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell100");
            this.tableCell101 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell101");
            this.tableCell102 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell102");
            this.tableCell103 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell103");
            this.tableCell104 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell104");
            this.tableCell105 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell105");
            this.tableCell106 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell106");
            this.tableCell107 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell107");
            this.tableCell108 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell108");
            this.tableCell109 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell109");
            this.tableCell110 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell110");
            this.tableCell111 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell111");
            this.tableCell112 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell112");
            this.tableCell113 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell113");
            this.tableCell114 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell114");
            this.tableCell115 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell115");
            this.tableCell116 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell116");
            this.tableCell117 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell117");
            this.tableCell118 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell118");
            this.tableCell119 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell119");
            this.tableCell120 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell120");
            this.tableCell121 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell121");
            this.tableCell122 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell122");
            this.tableCell123 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell123");
            this.tableCell124 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell124");
            this.tableCell125 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell125");
            this.tableCell126 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell126");
            this.tableCell127 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell127");
            this.tableCell128 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell128");
            this.tableCell129 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell129");
            this.tableCell130 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell130");
            this.tableCell131 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell131");
            this.tableCell1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell1");
            this.table3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table3");
            this.tableRow3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow3");
            this.tableCell67 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell67");
            this.tableCell68 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell68");
            this.tableCell69 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell69");
            this.tableCell70 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell70");
            this.tableCell71 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell71");
            this.tableCell72 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell72");
            this.tableCell73 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell73");
            this.tableCell74 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell74");
            this.tableCell75 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell75");
            this.tableCell76 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell76");
            this.tableCell77 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell77");
            this.tableCell78 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell78");
            this.tableCell79 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell79");
            this.tableCell80 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell80");
            this.tableCell81 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell81");
            this.tableCell82 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell82");
            this.tableCell83 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell83");
            this.tableCell84 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell84");
            this.tableCell85 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell85");
            this.tableCell86 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell86");
            this.tableCell87 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell87");
            this.tableCell88 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell88");
            this.tableCell89 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell89");
            this.tableCell90 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell90");
            this.tableCell91 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell91");
            this.tableCell92 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell92");
            this.tableCell93 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell93");
            this.tableCell94 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell94");
            this.tableCell95 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell95");
            this.tableCell96 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell96");
            this.tableCell97 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell97");
            this.tableCell98 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell98");
            this.tableCell2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell2");

            // Data Sources
            this.objectDataSource1 = reportInitializer.GetDataSource<DevExpress.DataAccess.ObjectBinding.ObjectDataSource>("objectDataSource1");
        }
        private DevExpress.XtraReports.UI.TopMarginBand TopMargin;
        private DevExpress.XtraReports.UI.BottomMarginBand BottomMargin;
        private DevExpress.XtraReports.UI.DetailBand Detail;
        private DevExpress.XtraReports.UI.PageFooterBand PageFooter;
        private DevExpress.XtraReports.UI.DetailReportBand DetailReport1;
        private DevExpress.XtraReports.UI.XRLabel label16;
        private DevExpress.XtraReports.UI.XRLabel label4;
        private DevExpress.XtraReports.UI.XRLabel label2;
        private DevExpress.XtraReports.UI.XRLabel label1;
        private DevExpress.XtraReports.UI.XRLabel label3;
        private DevExpress.XtraReports.UI.XRLabel label5;
        private DevExpress.XtraReports.UI.XRLabel label6;
        private DevExpress.XtraReports.UI.XRLabel label7;
        private DevExpress.XtraReports.UI.DetailBand Detail2;
        private DevExpress.XtraReports.UI.ReportHeaderBand ReportHeader1;
        private DevExpress.XtraReports.UI.XRTable table4;
        private DevExpress.XtraReports.UI.XRTableRow tableRow4;
        private DevExpress.XtraReports.UI.XRTableCell tableCell100;
        private DevExpress.XtraReports.UI.XRTableCell tableCell101;
        private DevExpress.XtraReports.UI.XRTableCell tableCell102;
        private DevExpress.XtraReports.UI.XRTableCell tableCell103;
        private DevExpress.XtraReports.UI.XRTableCell tableCell104;
        private DevExpress.XtraReports.UI.XRTableCell tableCell105;
        private DevExpress.XtraReports.UI.XRTableCell tableCell106;
        private DevExpress.XtraReports.UI.XRTableCell tableCell107;
        private DevExpress.XtraReports.UI.XRTableCell tableCell108;
        private DevExpress.XtraReports.UI.XRTableCell tableCell109;
        private DevExpress.XtraReports.UI.XRTableCell tableCell110;
        private DevExpress.XtraReports.UI.XRTableCell tableCell111;
        private DevExpress.XtraReports.UI.XRTableCell tableCell112;
        private DevExpress.XtraReports.UI.XRTableCell tableCell113;
        private DevExpress.XtraReports.UI.XRTableCell tableCell114;
        private DevExpress.XtraReports.UI.XRTableCell tableCell115;
        private DevExpress.XtraReports.UI.XRTableCell tableCell116;
        private DevExpress.XtraReports.UI.XRTableCell tableCell117;
        private DevExpress.XtraReports.UI.XRTableCell tableCell118;
        private DevExpress.XtraReports.UI.XRTableCell tableCell119;
        private DevExpress.XtraReports.UI.XRTableCell tableCell120;
        private DevExpress.XtraReports.UI.XRTableCell tableCell121;
        private DevExpress.XtraReports.UI.XRTableCell tableCell122;
        private DevExpress.XtraReports.UI.XRTableCell tableCell123;
        private DevExpress.XtraReports.UI.XRTableCell tableCell124;
        private DevExpress.XtraReports.UI.XRTableCell tableCell125;
        private DevExpress.XtraReports.UI.XRTableCell tableCell126;
        private DevExpress.XtraReports.UI.XRTableCell tableCell127;
        private DevExpress.XtraReports.UI.XRTableCell tableCell128;
        private DevExpress.XtraReports.UI.XRTableCell tableCell129;
        private DevExpress.XtraReports.UI.XRTableCell tableCell130;
        private DevExpress.XtraReports.UI.XRTableCell tableCell131;
        private DevExpress.XtraReports.UI.XRTableCell tableCell1;
        private DevExpress.XtraReports.UI.XRTable table3;
        private DevExpress.XtraReports.UI.XRTableRow tableRow3;
        private DevExpress.XtraReports.UI.XRTableCell tableCell67;
        private DevExpress.XtraReports.UI.XRTableCell tableCell68;
        private DevExpress.XtraReports.UI.XRTableCell tableCell69;
        private DevExpress.XtraReports.UI.XRTableCell tableCell70;
        private DevExpress.XtraReports.UI.XRTableCell tableCell71;
        private DevExpress.XtraReports.UI.XRTableCell tableCell72;
        private DevExpress.XtraReports.UI.XRTableCell tableCell73;
        private DevExpress.XtraReports.UI.XRTableCell tableCell74;
        private DevExpress.XtraReports.UI.XRTableCell tableCell75;
        private DevExpress.XtraReports.UI.XRTableCell tableCell76;
        private DevExpress.XtraReports.UI.XRTableCell tableCell77;
        private DevExpress.XtraReports.UI.XRTableCell tableCell78;
        private DevExpress.XtraReports.UI.XRTableCell tableCell79;
        private DevExpress.XtraReports.UI.XRTableCell tableCell80;
        private DevExpress.XtraReports.UI.XRTableCell tableCell81;
        private DevExpress.XtraReports.UI.XRTableCell tableCell82;
        private DevExpress.XtraReports.UI.XRTableCell tableCell83;
        private DevExpress.XtraReports.UI.XRTableCell tableCell84;
        private DevExpress.XtraReports.UI.XRTableCell tableCell85;
        private DevExpress.XtraReports.UI.XRTableCell tableCell86;
        private DevExpress.XtraReports.UI.XRTableCell tableCell87;
        private DevExpress.XtraReports.UI.XRTableCell tableCell88;
        private DevExpress.XtraReports.UI.XRTableCell tableCell89;
        private DevExpress.XtraReports.UI.XRTableCell tableCell90;
        private DevExpress.XtraReports.UI.XRTableCell tableCell91;
        private DevExpress.XtraReports.UI.XRTableCell tableCell92;
        private DevExpress.XtraReports.UI.XRTableCell tableCell93;
        private DevExpress.XtraReports.UI.XRTableCell tableCell94;
        private DevExpress.XtraReports.UI.XRTableCell tableCell95;
        private DevExpress.XtraReports.UI.XRTableCell tableCell96;
        private DevExpress.XtraReports.UI.XRTableCell tableCell97;
        private DevExpress.XtraReports.UI.XRTableCell tableCell98;
        private DevExpress.XtraReports.UI.XRTableCell tableCell2;
        private DevExpress.DataAccess.ObjectBinding.ObjectDataSource objectDataSource1;
    }
}
