// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HassyaAllrightCloud.Domain.Entities
{
    /// <summary>
    /// ETCデータ取込テーブル
    /// </summary>
    public partial class LkdEtcImport
    {
        /// <summary>
        /// ログＳＥＱ
        /// </summary>
        public int LogSeq { get; set; }
        /// <summary>
        /// ログ処理区分
        /// </summary>
        public byte LogShKbn { get; set; }
        /// <summary>
        /// 変更前キー項目
        /// </summary>
        public string HenKeyItm { get; set; }
        /// <summary>
        /// ファイル名
        /// </summary>
        public string FileName { get; set; }
        /// <summary>
        /// カード番号
        /// </summary>
        public string CardNo { get; set; }
        /// <summary>
        /// ＥＴＣ明細連番
        /// </summary>
        public short EtcRen { get; set; }
        /// <summary>
        /// 運行年月日
        /// </summary>
        public string UnkYmd { get; set; }
        /// <summary>
        /// 車輌コード
        /// </summary>
        public int SyaRyoCd { get; set; }
        /// <summary>
        /// 受付番号
        /// </summary>
        public string UkeNo { get; set; }
        /// <summary>
        /// 運行日連番
        /// </summary>
        public short UnkRen { get; set; }
        /// <summary>
        /// 悌団番号
        /// </summary>
        public short TeiDanNo { get; set; }
        /// <summary>
        /// 分割連番
        /// </summary>
        public short BunkRen { get; set; }
        /// <summary>
        /// 運行時間
        /// </summary>
        public string UnkTime { get; set; }
        /// <summary>
        /// 変更回数
        /// </summary>
        public short HenKai { get; set; }
        /// <summary>
        /// 付帯積込品コードＳＥＱ
        /// </summary>
        public int FutTumCdSeq { get; set; }
        /// <summary>
        /// 付帯積込品名
        /// </summary>
        public string FutTumNm { get; set; }
        /// <summary>
        /// 入料金所地区コード
        /// </summary>
        public byte IriRyoChiCd { get; set; }
        /// <summary>
        /// 入料金所コード
        /// </summary>
        public string IriRyoCd { get; set; }
        /// <summary>
        /// 出料金所地区コード
        /// </summary>
        public byte DeRyoChiCd { get; set; }
        /// <summary>
        /// 出料金所コード
        /// </summary>
        public string DeRyoCd { get; set; }
        /// <summary>
        /// 精算コードＳＥＱ
        /// </summary>
        public int SeisanCdSeq { get; set; }
        /// <summary>
        /// 精算名
        /// </summary>
        public string SeisanNm { get; set; }
        /// <summary>
        /// 精算区分
        /// </summary>
        public byte SeisanKbn { get; set; }
        /// <summary>
        /// 数量
        /// </summary>
        public short Suryo { get; set; }
        /// <summary>
        /// 単価
        /// </summary>
        public int TanKa { get; set; }
        /// <summary>
        /// 手数料率
        /// </summary>
        public decimal TesuRitu { get; set; }
        /// <summary>
        /// 手数料額
        /// </summary>
        public int SyaRyoTes { get; set; }
        /// <summary>
        /// 転送区分
        /// </summary>
        public byte TensoKbn { get; set; }
        /// <summary>
        /// 取込単価
        /// </summary>
        public int ImportTanka { get; set; }
        /// <summary>
        /// 備考
        /// </summary>
        public string BikoNm { get; set; }
        /// <summary>
        /// 拡張項目
        /// </summary>
        public string ExpItem { get; set; }
        /// <summary>
        /// 使用区分
        /// </summary>
        public byte SiyoKbn { get; set; }
        /// <summary>
        /// 最終更新年月日
        /// </summary>
        public string UpdYmd { get; set; }
        /// <summary>
        /// 最終更新時間
        /// </summary>
        public string UpdTime { get; set; }
        /// <summary>
        /// 最終更新社員コードＳＥＱ
        /// </summary>
        public int UpdSyainCd { get; set; }
        /// <summary>
        /// 最終更新プログラムＩＤ
        /// </summary>
        public string UpdPrgId { get; set; }
    }
}