// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HassyaAllrightCloud.Domain.Entities
{
    public partial class LkdFutTum
    {
        public int LogSeq { get; set; }
        public byte LogShKbn { get; set; }
        public string HenKeyItm { get; set; }
        public string UkeNo { get; set; }
        public short UnkRen { get; set; }
        public byte FutTumKbn { get; set; }
        public short FutTumRen { get; set; }
        public short HenKai { get; set; }
        public short Nittei { get; set; }
        public byte TomKbn { get; set; }
        public int FutTumCdSeq { get; set; }
        public string FutTumNm { get; set; }
        public string HasYmd { get; set; }
        public byte IriRyoChiCd { get; set; }
        public string IriRyoCd { get; set; }
        public string IriRyoNm { get; set; }
        public byte DeRyoChiCd { get; set; }
        public string DeRyoCd { get; set; }
        public string DeRyoNm { get; set; }
        public int SeisanCdSeq { get; set; }
        public string SeisanNm { get; set; }
        public byte SeisanKbn { get; set; }
        public int TanKa { get; set; }
        public short Suryo { get; set; }
        public int UriGakKin { get; set; }
        public byte ZeiKbn { get; set; }
        public decimal Zeiritsu { get; set; }
        public int SyaRyoSyo { get; set; }
        public decimal TesuRitu { get; set; }
        public int SyaRyoTes { get; set; }
        public byte NyuKinKbn { get; set; }
        public byte NcouKbn { get; set; }
        public string BikoNm { get; set; }
        public string ExpItem { get; set; }
        public byte SiyoKbn { get; set; }
        public string UpdYmd { get; set; }
        public string UpdTime { get; set; }
        public int UpdSyainCd { get; set; }
        public string UpdPrgId { get; set; }
    }
}