// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HassyaAllrightCloud.Domain.Entities
{
    public partial class LkdHenko
    {
        public int LogSeq { get; set; }
        public byte LogShKbn { get; set; }
        public string HenKeyItm { get; set; }
        public string UkeNo { get; set; }
        public byte YykSiyoFlg { get; set; }
        public short HaitaHenKai { get; set; }
        public string HenYmd { get; set; }
        public string HenTime { get; set; }
        public string UpdYmd { get; set; }
        public string UpdTime { get; set; }
        public int UpdSyainCd { get; set; }
        public string UpdPrgId { get; set; }
    }
}