// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HassyaAllrightCloud.Domain.Entities
{
    public partial class LkdKikyuj
    {
        public int LogSeq { get; set; }
        public byte LogShKbn { get; set; }
        public string HenKeyItm { get; set; }
        public int KinKyuTblCdSeq { get; set; }
        public short HenKai { get; set; }
        public int SyainCdSeq { get; set; }
        public string KinKyuSymd { get; set; }
        public string KinKyuStime { get; set; }
        public string KinKyuEymd { get; set; }
        public string KinKyuEtime { get; set; }
        public int KinKyuCdSeq { get; set; }
        public string BikoNm { get; set; }
        public byte SiyoKbn { get; set; }
        public string UpdYmd { get; set; }
        public string UpdTime { get; set; }
        public int UpdSyainCd { get; set; }
        public string UpdPrgId { get; set; }
    }
}