// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HassyaAllrightCloud.Domain.Entities
{
    public partial class LkdNyuSih
    {
        public int LogSeq { get; set; }
        public byte LogShKbn { get; set; }
        public string HenKeyItm { get; set; }
        public int NyuSihTblSeq { get; set; }
        public short HenKai { get; set; }
        public byte NyuSihKbn { get; set; }
        public string NyuSihYmd { get; set; }
        public int NyuSihEigSeq { get; set; }
        public byte NyuSihSyu { get; set; }
        public string CardSyo { get; set; }
        public string CardDen { get; set; }
        public int NyuSihG { get; set; }
        public int FuriTes { get; set; }
        public string BankCd { get; set; }
        public string BankSitCd { get; set; }
        public byte YokinSyu { get; set; }
        public string TegataYmd { get; set; }
        public string TegataNo { get; set; }
        public string EtcSyo1 { get; set; }
        public string EtcSyo2 { get; set; }
        public byte SiyoKbn { get; set; }
        public string UpdYmd { get; set; }
        public string UpdTime { get; set; }
        public int UpdSyainCd { get; set; }
        public string UpdPrgId { get; set; }
    }
}