// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HassyaAllrightCloud.Domain.Entities
{
    public partial class LkdNyShCu
    {
        public int LogSeq { get; set; }
        public byte LogShKbn { get; set; }
        public string HenKeyItm { get; set; }
        public string UkeNo { get; set; }
        public short NyuSihCouRen { get; set; }
        public short HenKai { get; set; }
        public byte NyuSihKbn { get; set; }
        public byte SeiFutSyu { get; set; }
        public byte NyuKesiKbn { get; set; }
        public short UnkRen { get; set; }
        public int YouTblSeq { get; set; }
        public int CouKesG { get; set; }
        public short FutTumRen { get; set; }
        public int CouTblSeq { get; set; }
        public byte SiyoKbn { get; set; }
        public string UpdYmd { get; set; }
        public string UpdTime { get; set; }
        public int UpdSyainCd { get; set; }
        public string UpdPrgId { get; set; }
    }
}