// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HassyaAllrightCloud.Domain.Entities
{
    public partial class LkdUnkobiExp
    {
        public int LogSeq { get; set; }
        public byte LogShKbn { get; set; }
        public string HenKeyItm { get; set; }
        public string UkeNo { get; set; }
        public short UnkRen { get; set; }
        public string HaiSkouKnm { get; set; }
        public string HaiSbinNm { get; set; }
        public string TouSkouKnm { get; set; }
        public string TouSbinNm { get; set; }
        public string ExpItem { get; set; }
    }
}