// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HassyaAllrightCloud.Domain.Entities
{
    public partial class LkdYyksho
    {
        public int LogSeq { get; set; }
        public byte LogShKbn { get; set; }
        public string HenKeyItm { get; set; }
        public string UkeNo { get; set; }
        public short HenKai { get; set; }
        public string UkeYmd { get; set; }
        public byte YoyaSyu { get; set; }
        public int YoyaKbnSeq { get; set; }
        public int KikakuNo { get; set; }
        public string TourCd { get; set; }
        public int KasTourCdSeq { get; set; }
        public int UkeEigCdSeq { get; set; }
        public int SeiEigCdSeq { get; set; }
        public int IraEigCdSeq { get; set; }
        public int EigTanCdSeq { get; set; }
        public int InTanCdSeq { get; set; }
        public string YoyaNm { get; set; }
        public string YoyaKana { get; set; }
        public int TokuiSeq { get; set; }
        public int SitenCdSeq { get; set; }
        public int SirCdSeq { get; set; }
        public int SirSitenCdSeq { get; set; }
        public string TokuiTel { get; set; }
        public string TokuiTanNm { get; set; }
        public string TokuiFax { get; set; }
        public string TokuiMail { get; set; }
        public decimal UntKin { get; set; }
        public byte ZeiKbn { get; set; }
        public decimal Zeiritsu { get; set; }
        public decimal ZeiRui { get; set; }
        public decimal TesuRitu { get; set; }
        public decimal TesuRyoG { get; set; }
        public int SeiKyuKbnSeq { get; set; }
        public string SeikYm { get; set; }
        public string SeiTaiYmd { get; set; }
        public decimal CanRit { get; set; }
        public int CanUnc { get; set; }
        public byte CanZkbn { get; set; }
        public decimal CanSyoR { get; set; }
        public int CanSyoG { get; set; }
        public string CanYmd { get; set; }
        public int CanTanSeq { get; set; }
        public string CanRiy { get; set; }
        public string CanFuYmd { get; set; }
        public int CanFuTanSeq { get; set; }
        public string CanFuRiy { get; set; }
        public int BikoTblSeq { get; set; }
        public byte Kskbn { get; set; }
        public byte KhinKbn { get; set; }
        public byte KaknKais { get; set; }
        public string KaktYmd { get; set; }
        public byte HaiSkbn { get; set; }
        public byte HaiIkbn { get; set; }
        public short GuiWnin { get; set; }
        public byte NippoKbn { get; set; }
        public byte YouKbn { get; set; }
        public byte NyuKinKbn { get; set; }
        public byte NcouKbn { get; set; }
        public byte SihKbn { get; set; }
        public byte ScouKbn { get; set; }
        public byte SiyoKbn { get; set; }
        public string UpdYmd { get; set; }
        public string UpdTime { get; set; }
        public int UpdSyainCd { get; set; }
        public string UpdPrgId { get; set; }
    }
}