// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HassyaAllrightCloud.Domain.Entities
{
    public partial class TkdBookingMaxMinFareFeeCalcMeisai
    {
        public string UkeNo { get; set; }
        public short UnkRen { get; set; }
        public short SyaSyuRen { get; set; }
        public short Nittei { get; set; }
        public string UnkYmd { get; set; }
        public decimal RunningKm { get; set; }
        public string InspectionStartYmd { get; set; }
        public string InspectionStartTime { get; set; }
        public string InspectionEndYmd { get; set; }
        public string InspectionEndTime { get; set; }
        public string RestraintTime { get; set; }
        public decimal ServiceKm { get; set; }
        public string ServiceTime { get; set; }
        public string MidnightEarlyMorningTime { get; set; }
        public byte ChangeDriverFeeFlag { get; set; }
        public decimal ChangeDriverRunningKm { get; set; }
        public string ChangeDriverRestraintTime { get; set; }
        public string ChangeDriverMidnightEarlyMorningTime { get; set; }
        public string UpdYmd { get; set; }
        public string UpdTime { get; set; }
        public int UpdSyainCd { get; set; }
        public string UpdPrgId { get; set; }
    }
}