// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HassyaAllrightCloud.Domain.Entities
{
    public partial class TkdBiko
    {
        public string UkeNo { get; set; }
        public int BikoTblSeq { get; set; }
        public short BikoRen { get; set; }
        public short HenKai { get; set; }
        public byte BikTblKbn { get; set; }
        public string BikoNm { get; set; }
        public byte SiyoKbn { get; set; }
        public string UpdYmd { get; set; }
        public string UpdTime { get; set; }
        public int UpdSyainCd { get; set; }
        public string UpdPrgId { get; set; }
    }
}