// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HassyaAllrightCloud.Domain.Entities
{
    public partial class TkdCoupon
    {
        public int CouTblSeq { get; set; }
        public short HenKai { get; set; }
        public byte NyuSihKbn { get; set; }
        public int SeiSihCdSeq { get; set; }
        public int SeiSihSitCdSeq { get; set; }
        public string HakoYmd { get; set; }
        public int NyuSihEigSeq { get; set; }
        public string CouNo { get; set; }
        public int CouGkin { get; set; }
        public byte CouZanFlg { get; set; }
        public int CouZan { get; set; }
        public byte SiyoKbn { get; set; }
        public int TenantCdSeq { get; set; }
        public string UpdYmd { get; set; }
        public string UpdTime { get; set; }
        public int UpdSyainCd { get; set; }
        public string UpdPrgId { get; set; }
    }
}