// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HassyaAllrightCloud.Domain.Entities
{
    public partial class TkdFavoriteMenu
    {
        public int FavoriteMenuCdSeq { get; set; }
        public int SyainCdSeq { get; set; }
        public string MenuTitle { get; set; }
        public string MenuUrl { get; set; }
        public short DisplayOrder { get; set; }
        public string UpdYmd { get; set; }
        public string UpdTime { get; set; }
        public int UpdSyainCd { get; set; }
        public string UpdPrgId { get; set; }
    }
}