// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HassyaAllrightCloud.Domain.Entities
{
    public partial class TkdFavoriteSite
    {
        public int FavoriteSiteCdSeq { get; set; }
        public int SyainCdSeq { get; set; }
        public string SiteTitle { get; set; }
        public string SiteUrl { get; set; }
        public short DisplayOrder { get; set; }
        public string UpdYmd { get; set; }
        public string UpdTime { get; set; }
        public int UpdSyainCd { get; set; }
        public string UpdPrgId { get; set; }
    }
}