// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HassyaAllrightCloud.Domain.Entities
{
    public partial class TkdHaiinMail
    {
        public string UkeNo { get; set; }
        public short UnkRen { get; set; }
        public short TeiDanNo { get; set; }
        public short BunkRen { get; set; }
        public byte HaiInRen { get; set; }
        public int SyainCdSeq { get; set; }
        public int KinKyuTblCdSeq { get; set; }
        public string UnkYmd { get; set; }
        public string ControlNo { get; set; }
        public byte MailExeCnt { get; set; }
        public byte LineExeCnt { get; set; }
        public byte SchReadKbn { get; set; }
        public string Biko { get; set; }
        public string UpdYmd { get; set; }
        public string UpdTime { get; set; }
        public int UpdSyainCd { get; set; }
        public string UpdPrgId { get; set; }
    }
}