// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HassyaAllrightCloud.Domain.Entities
{
    public partial class TkdHaiin
    {
        public string UkeNo { get; set; }
        public short UnkRen { get; set; }
        public short TeiDanNo { get; set; }
        public short BunkRen { get; set; }
        public byte HaiInRen { get; set; }
        public short HenKai { get; set; }
        public int SyainCdSeq { get; set; }
        public string SyukinTime { get; set; }
        public string TaiknTime { get; set; }
        public string Syukinbasy { get; set; }
        public string TaiknBasy { get; set; }
        public byte SyokumuKbn { get; set; }
        public int BikoTblSeq { get; set; }
        public byte SiyoKbn { get; set; }
        public string UpdYmd { get; set; }
        public string UpdTime { get; set; }
        public int UpdSyainCd { get; set; }
        public string UpdPrgId { get; set; }
    }
}