// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HassyaAllrightCloud.Domain.Entities
{
    public partial class TkdInpCon
    {
        public int SyainCdSeq { get; set; }
        public string FormNm { get; set; }
        public string ItemNm { get; set; }
        public string JoInput { get; set; }
        public byte NodeFlg { get; set; }
        public string UpdYmd { get; set; }
        public string UpdTime { get; set; }
        public int UpdSyainCd { get; set; }
        public string UpdPrgId { get; set; }
        public int FilterId { get; set; }
    }
}