// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HassyaAllrightCloud.Domain.Entities
{
    public partial class TkdJitHou
    {
        public byte UnsouKbn { get; set; }
        public string SyoriYm { get; set; }
        public int EigyoCdSeq { get; set; }
        public byte KataKbn { get; set; }
        public byte NenRyoKbn { get; set; }
        public int NobeJyoCnt { get; set; }
        public int NobeRinCnt { get; set; }
        public int NobeSumCnt { get; set; }
        public int NobeJitCnt { get; set; }
        public decimal JitudoRitu { get; set; }
        public decimal RinjiRitu { get; set; }
        public decimal JitJisaKm { get; set; }
        public decimal JitKisoKm { get; set; }
        public int YusoJin { get; set; }
        public int UnkoCnt { get; set; }
        public int UnkoKikak1Cnt { get; set; }
        public int UnkoKikak2Cnt { get; set; }
        public int UnkoOthCnt { get; set; }
        public decimal UnsoSyu { get; set; }
        public decimal DayTotalKm { get; set; }
        public decimal DayYusoJin { get; set; }
        public decimal DayUnsoSyu { get; set; }
        public decimal DayJisaKm { get; set; }
        public decimal UnsoZaSyu { get; set; }
        public string UpdYmd { get; set; }
        public string UpdTime { get; set; }
        public int UpdSyainCd { get; set; }
        public string UpdPrgId { get; set; }
    }
}