// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HassyaAllrightCloud.Domain.Entities
{
    public partial class TkdKaknin
    {
        public string UkeNo { get; set; }
        public short KaknRen { get; set; }
        public short HenKai { get; set; }
        public string KaknYmd { get; set; }
        public string KaknAit { get; set; }
        public short KaknNin { get; set; }
        public byte SaikFlg { get; set; }
        public byte DaiSuFlg { get; set; }
        public byte KingFlg { get; set; }
        public byte NitteiFlg { get; set; }
        public int BikoTblSeq { get; set; }
        public byte SiyoKbn { get; set; }
        public string UpdYmd { get; set; }
        public string UpdTime { get; set; }
        public int UpdSyainCd { get; set; }
        public string UpdPrgId { get; set; }
    }
}