// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HassyaAllrightCloud.Domain.Entities
{
    public partial class TkdKoteik
    {
        /// <summary>
        /// 受付番号
        /// </summary>
        public string UkeNo { get; set; }
        /// <summary>
        /// 運行日連番
        /// </summary>
        public short UnkRen { get; set; }
        /// <summary>
        /// 悌団番号
        /// </summary>
        public short TeiDanNo { get; set; }
        /// <summary>
        /// 分割連番
        /// </summary>
        public short BunkRen { get; set; }
        /// <summary>
        /// 泊区分
        /// </summary>
        public byte TomKbn { get; set; }
        /// <summary>
        /// 日程
        /// </summary>
        public short Nittei { get; set; }
        /// <summary>
        /// 変更回数
        /// </summary>
        public short HenKai { get; set; }
        /// <summary>
        /// 悌団日程
        /// </summary>
        public short TeiDanNittei { get; set; }
        /// <summary>
        /// 悌団泊区分
        /// </summary>
        public byte TeiDanTomKbn { get; set; }
        /// <summary>
        /// 出庫営業所コードＳＥＱ
        /// </summary>
        public int SyuEigCdSeq { get; set; }
        /// <summary>
        /// 出庫地名
        /// </summary>
        public string SyukoNm { get; set; }
        public string SyukoTime { get; set; }
        /// <summary>
        /// 配車時間
        /// </summary>
        public string HaiStime { get; set; }
        /// <summary>
        /// 出発地コードＳＥＱ
        /// </summary>
        public int SyuPaCdSeq { get; set; }
        /// <summary>
        /// 出発地名
        /// </summary>
        public string SyuPaNm { get; set; }
        /// <summary>
        /// 出発時間
        /// </summary>
        public string SyuPaTime { get; set; }
        /// <summary>
        /// 経由地マップコードＳＥＱ
        /// </summary>
        public int KeiyuMapCdSeq { get; set; }
        /// <summary>
        /// 経由地名
        /// </summary>
        public string KeiyuNm { get; set; }
        /// <summary>
        /// 到着地コードＳＥＱ
        /// </summary>
        public int TouCdSeq { get; set; }
        /// <summary>
        /// 到着地名
        /// </summary>
        public string TouNm { get; set; }
        /// <summary>
        /// 到着時間
        /// </summary>
        public string TouChTime { get; set; }
        /// <summary>
        /// 帰庫営業所コードＳＥＱ
        /// </summary>
        public int KikEigSeq { get; set; }
        /// <summary>
        /// 帰庫地名
        /// </summary>
        public string KikoNm { get; set; }
        public string KikTime { get; set; }
        /// <summary>
        /// 宿泊地マップコードＳＥＱ
        /// </summary>
        public int ShakuMapCdSeq { get; set; }
        /// <summary>
        /// 宿泊地名
        /// </summary>
        public string ShakuNm { get; set; }
        /// <summary>
        /// 待機時間
        /// </summary>
        public string TaikTime { get; set; }
        /// <summary>
        /// 休憩地マップコードＳＥＱ
        /// </summary>
        public int KyuKmapCdSeq { get; set; }
        /// <summary>
        /// 休憩地名
        /// </summary>
        public string KyuKnm { get; set; }
        /// <summary>
        /// 休憩時間
        /// </summary>
        public string KyuKtime { get; set; }
        /// <summary>
        /// 休憩開始時間
        /// </summary>
        public string KyuKstaTime { get; set; }
        /// <summary>
        /// 休憩終了時間
        /// </summary>
        public string KyuKendTime { get; set; }
        /// <summary>
        /// 備考
        /// </summary>
        public string BikoNm { get; set; }
        /// <summary>
        /// 実車一般キロ
        /// </summary>
        public decimal JisaIpkm { get; set; }
        /// <summary>
        /// 実車高速キロ
        /// </summary>
        public decimal JisaKskm { get; set; }
        /// <summary>
        /// 回送一般キロ
        /// </summary>
        public decimal KisoIpkm { get; set; }
        /// <summary>
        /// 回送高速キロ
        /// </summary>
        public decimal KisoKokm { get; set; }
        /// <summary>
        /// 使用区分
        /// </summary>
        public byte SiyoKbn { get; set; }
        /// <summary>
        /// 最終更新年月日
        /// </summary>
        public string UpdYmd { get; set; }
        /// <summary>
        /// 最終更新時間
        /// </summary>
        public string UpdTime { get; set; }
        /// <summary>
        /// 最終更新社員コードＳＥＱ
        /// </summary>
        public int UpdSyainCd { get; set; }
        /// <summary>
        /// 最終更新プログラムＩＤ
        /// </summary>
        public string UpdPrgId { get; set; }
    }
}