// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HassyaAllrightCloud.Domain.Entities
{
    public partial class TkdKoban
    {
        public string UnkYmd { get; set; }
        public int SyainCdSeq { get; set; }
        public short KouBnRen { get; set; }
        public short HenKai { get; set; }
        public byte SyugyoKbn { get; set; }
        public int KinKyuTblCdSeq { get; set; }
        public string UkeNo { get; set; }
        public short UnkRen { get; set; }
        public short SyaSyuRen { get; set; }
        public short TeiDanNo { get; set; }
        public short BunkRen { get; set; }
        public int RotCdSeq { get; set; }
        public int RenEigCd { get; set; }
        public byte SigySyu { get; set; }
        public string KitYmd { get; set; }
        public byte SigyKbn { get; set; }
        public string SigyCd { get; set; }
        public string SyukinTime { get; set; }
        public string TaiknTime { get; set; }
        public string Syukinbasy { get; set; }
        public string TaiknBasy { get; set; }
        public byte KouZokPtnKbn { get; set; }
        public string SyukinYmd { get; set; }
        public string TaikinYmd { get; set; }
        public string FuriYmd { get; set; }
        public string RouTime { get; set; }
        public string KouStime { get; set; }
        public string TaikTime { get; set; }
        public string KyuKtime { get; set; }
        public string JitdTime { get; set; }
        public string ZangTime { get; set; }
        public string UsinyTime { get; set; }
        public string SsinTime { get; set; }
        public string BikoNm { get; set; }
        public byte SiyoKbn { get; set; }
        public string UpdYmd { get; set; }
        public string UpdTime { get; set; }
        public int UpdSyainCd { get; set; }
        public string UpdPrgId { get; set; }
    }
}