// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HassyaAllrightCloud.Domain.Entities
{
    public partial class TkdMihrim
    {
        public string UkeNo { get; set; }
        public short MihRen { get; set; }
        public short HenKai { get; set; }
        public byte SihFutSyu { get; set; }
        public short UnkRen { get; set; }
        public int YouTblSeq { get; set; }
        public int HaseiKin { get; set; }
        public int SyaRyoSyo { get; set; }
        public int SyaRyoTes { get; set; }
        public int YoushaGak { get; set; }
        public decimal SihRaiRui { get; set; }
        public int CouKesRui { get; set; }
        public short YouFutTumRen { get; set; }
        public byte SiyoKbn { get; set; }
        public string UpdYmd { get; set; }
        public string UpdTime { get; set; }
        public int UpdSyainCd { get; set; }
        public string UpdPrgId { get; set; }
    }
}