// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HassyaAllrightCloud.Domain.Entities
{
    public partial class TkdNotiReplyToken
    {
        public string ControlNo { get; set; }
        public byte NotiMethodKbn { get; set; }
        public string Token { get; set; }
        public string ExpiredDate { get; set; }
        public string ExpiredTime { get; set; }
        public byte SiyoKbn { get; set; }
        public string UpdYmd { get; set; }
        public string UpdTime { get; set; }
        public int UpdSyainCd { get; set; }
        public string UpdPrgId { get; set; }
    }
}