// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HassyaAllrightCloud.Domain.Entities
{
    public partial class TkdNotification
    {
        public string ControlNo { get; set; }
        public int SyainCdSeq { get; set; }
        public string SouSymd { get; set; }
        public string SouStime { get; set; }
        public short SouSren { get; set; }
        public byte MailNowKbn { get; set; }
        public byte LineNowKbn { get; set; }
        public string UpdYmd { get; set; }
        public string UpdTime { get; set; }
        public int UpdSyainCd { get; set; }
        public string UpdPrgId { get; set; }
    }
}