// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HassyaAllrightCloud.Domain.Entities
{
    public partial class TkdRyoshu
    {
        public int RyoOutSeq { get; set; }
        public short RyoRen { get; set; }
        public int SeiOutSeq { get; set; }
        public short SeiRen { get; set; }
        public byte SiyoKbn { get; set; }
        public string UpdYmd { get; set; }
        public string UpdTime { get; set; }
        public int UpdSyainCd { get; set; }
        public string UpdPrgId { get; set; }
        public int TenantCdSeq { get; set; }
    }
}