// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HassyaAllrightCloud.Domain.Entities
{
    public partial class TkdSeiPrS
    {
        public int SeiOutSeq { get; set; }
        public string SeikYm { get; set; }
        public string SeiHatYmd { get; set; }
        public string SeiOutTime { get; set; }
        public int InTanCdSeq { get; set; }
        public byte SeiOutSyKbn { get; set; }
        public byte SeiGenFlg { get; set; }
        public string StaUkeNo { get; set; }
        public string EndUkeNo { get; set; }
        public byte StaYoyaKbn { get; set; }
        public byte EndYoyaKbn { get; set; }
        public int SeiEigCdSeq { get; set; }
        public byte SeiSitKbn { get; set; }
        public int StaSeiCdSeq { get; set; }
        public int StaSeiSitCdSeq { get; set; }
        public int EndSeiCdSeq { get; set; }
        public int EndSeiSitCdSeq { get; set; }
        public byte SimeD { get; set; }
        public byte PrnCpys { get; set; }
        public byte PrnCpysTan { get; set; }
        public byte TesPrnKbn { get; set; }
        public byte SeiFutUncKbn { get; set; }
        public byte SeiFutFutKbn { get; set; }
        public byte SeiFutTukKbn { get; set; }
        public byte SeiFutTehKbn { get; set; }
        public byte SeiFutGuiKbn { get; set; }
        public byte SeiFutTumKbn { get; set; }
        public byte SeiFutCanKbn { get; set; }
        public string ZipCd { get; set; }
        public string Jyus1 { get; set; }
        public string Jyus2 { get; set; }
        public string TokuiNm { get; set; }
        public string SitenNm { get; set; }
        public byte SiyoKbn { get; set; }
        public string UpdYmd { get; set; }
        public string UpdTime { get; set; }
        public int UpdSyainCd { get; set; }
        public string UpdPrgId { get; set; }
        public int TenantCdSeq { get; set; }
    }
}