// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HassyaAllrightCloud.Domain.Entities
{
    public partial class TkdSeiMei
    {
        /// <summary>
        /// 請求書出力ＳＥＱ
        /// </summary>
        public int SeiOutSeq { get; set; }
        /// <summary>
        /// 請求書連番
        /// </summary>
        public short SeiRen { get; set; }
        /// <summary>
        /// 請求書明細連番
        /// </summary>
        public short SeiMeiRen { get; set; }
        /// <summary>
        /// 受付番号
        /// </summary>
        public string UkeNo { get; set; }
        /// <summary>
        /// 未収明細連番
        /// </summary>
        public short MisyuRen { get; set; }
        /// <summary>
        /// 売上額
        /// </summary>
        public int UriGakKin { get; set; }
        /// <summary>
        /// 消費税額
        /// </summary>
        public int SyaRyoSyo { get; set; }
        /// <summary>
        /// 手数料額
        /// </summary>
        public int SyaRyoTes { get; set; }
        /// <summary>
        /// 請求額
        /// </summary>
        public int SeiKin { get; set; }
        /// <summary>
        /// 入金累計
        /// </summary>
        public decimal NyuKinRui { get; set; }
        /// <summary>
        /// 請求書再発行区分
        /// </summary>
        public byte SeiSaHkbn { get; set; }
        /// <summary>
        /// 消費税率
        /// </summary>
        public decimal Zeiritsu { get; set; }
        /// <summary>
        /// 使用区分
        /// </summary>
        public byte SiyoKbn { get; set; }
        /// <summary>
        /// 最終更新年月日
        /// </summary>
        public string UpdYmd { get; set; }
        /// <summary>
        /// 最終更新時間
        /// </summary>
        public string UpdTime { get; set; }
        /// <summary>
        /// 最終更新社員コードＳＥＱ
        /// </summary>
        public int UpdSyainCd { get; set; }
        /// <summary>
        /// 最終更新プログラムＩＤ
        /// </summary>
        public string UpdPrgId { get; set; }
        public int TenantCdSeq { get; set; }

    }
}