// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HassyaAllrightCloud.Domain.Entities
{
    public partial class TkdShuri
    {
        public int ShuriTblSeq { get; set; }
        public short HenKai { get; set; }
        public int SyaRyoCdSeq { get; set; }
        public string ShuriSymd { get; set; }
        public string ShuriStime { get; set; }
        public string ShuriEymd { get; set; }
        public string ShuriEtime { get; set; }
        public int ShuriCdSeq { get; set; }
        public string BikoNm { get; set; }
        public byte SiyoKbn { get; set; }
        public string UpdYmd { get; set; }
        public string UpdTime { get; set; }
        public int UpdSyainCd { get; set; }
        public string UpdPrgId { get; set; }
    }
}