// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HassyaAllrightCloud.Domain.Entities
{
    public partial class TkdShabni
    {
        public string UkeNo { get; set; }
        public short UnkRen { get; set; }
        public short TeiDanNo { get; set; }
        public short BunkRen { get; set; }
        public string UnkYmd { get; set; }
        public short HenKai { get; set; }
        public decimal StMeter { get; set; }
        public decimal EndMeter { get; set; }
        public decimal JisaIpkm { get; set; }
        public decimal JisaKskm { get; set; }
        public decimal KisoIpkm { get; set; }
        public decimal KisoKokm { get; set; }
        public decimal OthKm { get; set; }
        public int NenryoCd1Seq { get; set; }
        public decimal Nenryo1 { get; set; }
        public int NenryoCd2Seq { get; set; }
        public decimal Nenryo2 { get; set; }
        public int NenryoCd3Seq { get; set; }
        public decimal Nenryo3 { get; set; }
        public short JyoSyaJin { get; set; }
        public short PlusJin { get; set; }
        public int NenryoDai { get; set; }
        public byte ZeiKbn { get; set; }
        public decimal Zeiritsu { get; set; }
        public int SyaRyoSyo { get; set; }
        public string SyuKoTime { get; set; }
        public string SyuPaTime { get; set; }
        public string KikTime { get; set; }
        public string TouChTime { get; set; }
        public string KoskuTime { get; set; }
        public string JisTime { get; set; }
        public byte UnkKai { get; set; }
        public string InspectionTime { get; set; }
        public int FeeMaxAmount { get; set; }
        public int FeeMinAmount { get; set; }
        public int FareMaxAmount { get; set; }
        public int FareMinAmount { get; set; }
        public int FareFeeMaxAmount { get; set; }
        public int FareFeeMinAmount { get; set; }
        public byte SiyoKbn { get; set; }
        public string UpdYmd { get; set; }
        public string UpdTime { get; set; }
        public int UpdSyainCd { get; set; }
        public string UpdPrgId { get; set; }
    }
}