// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HassyaAllrightCloud.Domain.Entities
{
    public partial class TkdSeiUch
    {
        public int SeiOutSeq { get; set; }
        public short SeiRen { get; set; }
        public short SeiMeiRen { get; set; }
        public short SeiUchRen { get; set; }
        public string HasYmd { get; set; }
        public string YoyaNm { get; set; }
        public string FutTumNm { get; set; }
        public string HaiSymd { get; set; }
        public string TouYmd { get; set; }
        public short Suryo { get; set; }
        public int TanKa { get; set; }
        public string SyaSyuNm { get; set; }
        public byte SiyoKbn { get; set; }
        public string UpdYmd { get; set; }
        public string UpdTime { get; set; }
        public int UpdSyainCd { get; set; }
        public string UpdPrgId { get; set; }
        public int TenantCdSeq { get; set; }
    }
}