// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HassyaAllrightCloud.Domain.Entities
{
    public partial class TkdUnkobiFile
    {
        public int TenantCdSeq { get; set; }
        public string UkeNo { get; set; }
        public short UnkRen { get; set; }
        public int FileNo { get; set; }
        public byte SiyoKbn { get; set; }
        public string UpdYmd { get; set; }
        public string UpdTime { get; set; }
        public int UpdSyainCd { get; set; }
        public string UpdPrgId { get; set; }
        public string FolderId { get; set; }
        public string FileId { get; set; }
    }
}