// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HassyaAllrightCloud.Domain.Entities
{
    public partial class TkdUnkobi
    {
        public string UkeNo { get; set; }
        public short UnkRen { get; set; }
        public short HenKai { get; set; }
        public string HaiSymd { get; set; }
        public string HaiStime { get; set; }
        /// <summary>
        /// 到着年月日
        /// </summary>
        public string TouYmd { get; set; }
        /// <summary>
        /// 到着時間
        /// </summary>
        public string TouChTime { get; set; }
        /// <summary>
        /// 表示到着年月日
        /// </summary>
        public string DispTouYmd { get; set; }
        /// <summary>
        /// 表示到着時間
        /// </summary>
        public string DispTouChTime { get; set; }
        public string SyuPaYmd { get; set; }
        public string SyuPaTime { get; set; }
        public string DispSyuPaYmd { get; set; }
        public string DispSyuPaTime { get; set; }
        public string UriYmd { get; set; }
        public string KanJnm { get; set; }
        public string KanjJyus1 { get; set; }
        public string KanjJyus2 { get; set; }
        public string KanjTel { get; set; }
        public string KanjFax { get; set; }
        public string KanjKeiNo { get; set; }
        public string KanjMail { get; set; }
        public byte KanDmhflg { get; set; }
        public string DanTaNm { get; set; }
        public string DanTaKana { get; set; }
        public int IkMapCdSeq { get; set; }
        public string IkNm { get; set; }
        public int HaiScdSeq { get; set; }
        public string HaiSnm { get; set; }
        public string HaiSjyus1 { get; set; }
        public string HaiSjyus2 { get; set; }
        public int HaiSkouKcdSeq { get; set; }
        public int HaiSbinCdSeq { get; set; }
        public string HaiSsetTime { get; set; }
        public int TouCdSeq { get; set; }
        public string TouNm { get; set; }
        public string TouJyusyo1 { get; set; }
        public string TouJyusyo2 { get; set; }
        public int TouKouKcdSeq { get; set; }
        public int TouBinCdSeq { get; set; }
        public string TouSetTime { get; set; }
        public int AreaMapSeq { get; set; }
        public string AreaNm { get; set; }
        public int HasMapCdSeq { get; set; }
        public string HasNm { get; set; }
        public int JyoKyakuCdSeq { get; set; }
        public short JyoSyaJin { get; set; }
        public short PlusJin { get; set; }
        public short DrvJin { get; set; }
        public short GuiSu { get; set; }
        public byte OthJinKbn1 { get; set; }
        public short OthJin1 { get; set; }
        public byte OthJinKbn2 { get; set; }
        public short OthJin2 { get; set; }
        public byte Kskbn { get; set; }
        public byte KhinKbn { get; set; }
        public byte HaiSkbn { get; set; }
        public byte HaiIkbn { get; set; }
        public short GuiWnin { get; set; }
        public byte NippoKbn { get; set; }
        public byte YouKbn { get; set; }
        public byte UkeJyKbnCd { get; set; }
        public byte SijJoKbn1 { get; set; }
        public byte SijJoKbn2 { get; set; }
        public byte SijJoKbn3 { get; set; }
        public byte SijJoKbn4 { get; set; }
        public byte SijJoKbn5 { get; set; }
        public int RotCdSeq { get; set; }
        public byte ZenHaFlg { get; set; }
        public byte KhakFlg { get; set; }
        public byte UnkoJkbn { get; set; }
        public string SyukoYmd { get; set; }
        public string SyuKoTime { get; set; }
        /// <summary>
        /// 帰庫日
        /// </summary>
        public string KikYmd { get; set; }
        /// <summary>
        /// 帰庫時間
        /// </summary>
        public string KikTime { get; set; }
        /// <summary>
        /// 表示帰庫日
        /// </summary>
        public string DispKikYmd { get; set; }
        /// <summary>
        /// 表示帰庫時間
        /// </summary>
        public string DispKikTime { get; set; }
        public int BikoTblSeq { get; set; }
        public string BikoNm { get; set; }
        /// <summary>
        /// 配車地交通機関名
        /// </summary>
        public string HaiSkouKnm { get; set; }
        /// <summary>
        /// 配車地便名
        /// </summary>
        public string HaiSbinNm { get; set; }
        /// <summary>
        /// 到着地交通機関名
        /// </summary>
        public string TouSkouKnm { get; set; }
        /// <summary>
        /// 到着地便名
        /// </summary>
        public string TouSbinNm { get; set; }
        public string UnsoOutputYmd { get; set; }
        public int UnsoAllKiro { get; set; }
        public int UnsoJitKiro { get; set; }
        public string UnsoAllTim { get; set; }
        public string UnsoJitTim { get; set; }
        public string UnsoShinSoTime { get; set; }
        public byte UnsoChangeFlg { get; set; }
        public byte UnsoSpecialFlg { get; set; }
        public int UnsoSanSyuEigCdSeq { get; set; }
        public string UnsoUnkStaTime { get; set; }
        public string UnsoUnkEndTime { get; set; }
        public int SinSoRyokin { get; set; }
        public int ChangeRyokin { get; set; }
        public int SpecialRyokin { get; set; }
        public byte WaribikiKbn { get; set; }
        public byte UnsoNenKeiyakuFlg { get; set; }
        public int UpperLimitFare { get; set; }
        public int LowerLimitFare { get; set; }
        public int UpperLimitFee { get; set; }
        public int LowerLimitFee { get; set; }
        public string OtherSystemCoperateCode { get; set; }
        public string CustomItems1 { get; set; }
        public string CustomItems2 { get; set; }
        public string CustomItems3 { get; set; }
        public string CustomItems4 { get; set; }
        public string CustomItems5 { get; set; }
        public string CustomItems6 { get; set; }
        public string CustomItems7 { get; set; }
        public string CustomItems8 { get; set; }
        public string CustomItems9 { get; set; }
        public string CustomItems10 { get; set; }
        public string CustomItems11 { get; set; }
        public string CustomItems12 { get; set; }
        public string CustomItems13 { get; set; }
        public string CustomItems14 { get; set; }
        public string CustomItems15 { get; set; }
        public string CustomItems16 { get; set; }
        public string CustomItems17 { get; set; }
        public string CustomItems18 { get; set; }
        public string CustomItems19 { get; set; }
        public string CustomItems20 { get; set; }
        public decimal? UnitPriceIndex { get; set; }
        public byte SiyoKbn { get; set; }
        public string UpdYmd { get; set; }
        public string UpdTime { get; set; }
        public int UpdSyainCd { get; set; }
        public string UpdPrgId { get; set; }
    }
}