// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HassyaAllrightCloud.Domain.Entities
{
    public partial class TkdYoushaNotice
    {
        public int MotoTenantCdSeq { get; set; }
        public string MotoUkeNo { get; set; }
        public short MotoUnkRen { get; set; }
        public int MotoYouTblSeq { get; set; }
        public string HaiSYmd { get; set; }
        public string HaiSTime { get; set; }
        public string TouYmd { get; set; }
        public string TouChTime { get; set; }
        public short? BigtypeNum { get; set; }
        public short? MediumtypeNum { get; set; }
        public short? SmalltypeNum { get; set; }
        public string DanTaNm { get; set; }
        public int? UkeTenantCdSeq { get; set; }
        public int? MotoTokuiSeq { get; set; }
        public int? MotoSitenCdSeq { get; set; }
        public byte? UnReadKbn { get; set; }
        public byte? RegiterKbn { get; set; }
        public byte? SiyoKbn { get; set; }
        public string UpdYmd { get; set; }
        public string UpdTime { get; set; }
        public int? UpdSyainCd { get; set; }
        public string UpdPrgId { get; set; }
    }
}