// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HassyaAllrightCloud.Domain.Entities
{
    public partial class TkdYousha
    {
        public string UkeNo { get; set; }
        public short UnkRen { get; set; }
        public int YouTblSeq { get; set; }
        public short HenKai { get; set; }
        public int YouCdSeq { get; set; }
        public int YouSitCdSeq { get; set; }
        public string HasYmd { get; set; }
        public string SihYotYmd { get; set; }
        public string SihYm { get; set; }
        public int SyaRyoUnc { get; set; }
        public byte ZeiKbn { get; set; }
        public decimal Zeiritsu { get; set; }
        public int SyaRyoSyo { get; set; }
        public decimal TesuRitu { get; set; }
        public int SyaRyoTes { get; set; }
        public byte JitaFlg { get; set; }
        public int CompanyCdSeq { get; set; }
        public byte SihKbn { get; set; }
        public byte ScouKbn { get; set; }
        public byte SiyoKbn { get; set; }
        public string UpdYmd { get; set; }
        public string UpdTime { get; set; }
        public int UpdSyainCd { get; set; }
        public string UpdPrgId { get; set; }
    }
}