// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HassyaAllrightCloud.Domain.Entities
{
    public partial class VkHaishaFutTum1
    {
        public string UkeNo { get; set; }
        public short UnkRen { get; set; }
        public short TeiDanNo { get; set; }
        public short BunkRen { get; set; }
        public string SeiTaiYmd { get; set; }
        public string SyukoYmd { get; set; }
        public string HaiSymd { get; set; }
        public string TouYmd { get; set; }
        public string KikYmd { get; set; }
        public int YouTblSeq { get; set; }
        public int SyuEigCdSeq { get; set; }
        public int HaiSsryCdSeq { get; set; }
        public int HaiSsryEigyoCdSeq { get; set; }
        public byte FutTumKbn { get; set; }
        public int FutTumCdSeq { get; set; }
        public string FutTumNm { get; set; }
        public byte FutGuiKbn { get; set; }
        public int? UriGakKin { get; set; }
        public int? SyaRyoSyo { get; set; }
        public int? SyaRyoTes { get; set; }
        public decimal TesuRitu { get; set; }
    }
}