// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HassyaAllrightCloud.Domain.Entities
{
    public partial class VpmBasyo
    {
        public int BasyoKenCdSeq { get; set; }
        public int BasyoMapCdSeq { get; set; }
        public string BasyoMapCd { get; set; }
        public string BasyoNm { get; set; }
        public string RyakuNm { get; set; }
        public byte SiyoIkiKbn { get; set; }
        public byte SiyoKouKbn { get; set; }
        public byte SiyoTehKbn { get; set; }
        public byte SiyoAreaKbn { get; set; }
        public byte SiyoHseiKbn { get; set; }
        public string ZipCd { get; set; }
        public string Jyus1 { get; set; }
        public string Jyus2 { get; set; }
        public string TelNo { get; set; }
        public string FaxNo { get; set; }
        public string BasyoTanNm { get; set; }
        public int BunruiCdSeq { get; set; }
        public int TehaiCdSeq { get; set; }
        public int TenantCdSeq { get; set; }
        public byte SiyoKbn { get; set; }
        public string UpdYmd { get; set; }
        public string UpdTime { get; set; }
        public int UpdSyainCd { get; set; }
        public string UpdPrgId { get; set; }
    }
}