// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HassyaAllrightCloud.Domain.Entities
{
    public partial class VpmCustomItems
    {
        public int TenantCdSeq { get; set; }
        public int CustomItemsNo { get; set; }
        public string CustomName { get; set; }
        public string Description { get; set; }
        public byte FormatKbn { get; set; }
        public byte RequiredItemFlg { get; set; }
        public int TextLengh { get; set; }
        public byte NumberRangeLimitFlg { get; set; }
        public int NumberRangeOrMore { get; set; }
        public int NumberRangeOrLess { get; set; }
        public byte NumberInitialValueFlg { get; set; }
        public int NumberInitialValue { get; set; }
        public byte NumberUnitFlg { get; set; }
        public string NumberUnit { get; set; }
        public byte NumberRoundKbn { get; set; }
        public byte NumberFloatFlg { get; set; }
        public int NumberScale { get; set; }
        public byte DatetimeRangeLimitFlg { get; set; }
        public string DatetimeRangeLimitStartYmd { get; set; }
        public string DatetimeRangeLimitEndYmd { get; set; }
        public byte DatetimeInitialValueFlg { get; set; }
        public byte DatetimeInitialValueKbn { get; set; }
        public byte DateTimeDisplayFormatKbn { get; set; }
        public byte TimeRangeLimitFlg { get; set; }
        public string TimeRangeLimitStartTime { get; set; }
        public string TimeRangeLimitEndTime { get; set; }
        public byte TimeInitialValueFlg { get; set; }
        public byte TimeInitialValueKbn { get; set; }
        public string UpdYmd { get; set; }
        public string UpdTime { get; set; }
        public int UpdSyainCd { get; set; }
        public string UpdPrgId { get; set; }
        public string CodeSyu { get; set; }
    }
}