// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HassyaAllrightCloud.Domain.Entities
{
    public partial class VpmCodeKb
    {
        public int TenantCdSeq { get; set; }
        public int CodeKbnSeq { get; set; }
        public string CodeSyu { get; set; }
        public string CodeKbn { get; set; }
        public string CodeKbnNm { get; set; }
        public string RyakuNm { get; set; }
        public string CodeSeiKbn { get; set; }
        public byte SiyoKbn { get; set; }
        public string UpdYmd { get; set; }
        public string UpdTime { get; set; }
        public int UpdSyainCd { get; set; }
        public string UpdPrgId { get; set; }
    }
}