// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HassyaAllrightCloud.Domain.Entities
{
    public partial class VpmFutai
    {
        public int FutaiCdSeq { get; set; }
        public int TenantCdSeq { get; set; }
        public short FutaiCd { get; set; }
        public string FutaiNm { get; set; }
        public string RyakuNm { get; set; }
        public byte FutGuiKbn { get; set; }
        public byte ZeiHyoKbn { get; set; }
        public int ItSehCode { get; set; }
        public int ItSesCode { get; set; }
        public int ItSeuCode { get; set; }
        public byte SiyoKbn { get; set; }
        public string UpdYmd { get; set; }
        public string UpdTime { get; set; }
        public int UpdSyainCd { get; set; }
        public string UpdPrgId { get; set; }
    }
}