// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HassyaAllrightCloud.Domain.Entities
{
    public partial class VpmKinKyu
    {
        public int TenantCdSeq { get; set; }
        public int KinKyuCdSeq { get; set; }
        public short KinKyuCd { get; set; }
        public string KinKyuNm { get; set; }
        public string RyakuNm { get; set; }
        public byte KinKyuKbn { get; set; }
        public string ColKinKyu { get; set; }
        public string KyuSyukinNm { get; set; }
        public string KyuSyukinRyaku { get; set; }
        public string DefaultSyukinTime { get; set; }
        public string DefaultTaiknTime { get; set; }
        public byte KyusyutsuKbn { get; set; }
        public byte SiyoKbn { get; set; }
        public string UpdYmd { get; set; }
        public string UpdTime { get; set; }
        public int UpdSyainCd { get; set; }
        public string UpdPrgId { get; set; }
    }
}