// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HassyaAllrightCloud.Domain.Entities
{
    public partial class VpmNotiTemplateVar
    {
        public byte TemplateKbn { get; set; }
        public string VariableCd { get; set; }
        public string VariableNm { get; set; }
        public byte MailSiyoKbn { get; set; }
        public byte LineSiyoKbn { get; set; }
        public string UpdYmd { get; set; }
        public string UpdTime { get; set; }
        public int UpdSyainCd { get; set; }
        public string UpdPrgId { get; set; }
    }
}