// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HassyaAllrightCloud.Domain.Entities
{
    public partial class VpmRyokinSplit
    {
        public byte TargetEntranceRyokinTikuCd { get; set; }
        public string TargetEntranceRyokinCd { get; set; }
        public byte TargetExitRyokinTikuCd { get; set; }
        public string TargetExitRyokinCd { get; set; }
        public int DividedNumber { get; set; }
        public byte EntranceRyokinTikuCd { get; set; }
        public string EntranceRyokinCd { get; set; }
        public byte ExitRyokinTikuCd { get; set; }
        public string ExitRyokinCd { get; set; }
        public int Fee { get; set; }
        public int Fee2 { get; set; }
        public int Fee3 { get; set; }
        public int Fee4 { get; set; }
        public int Fee5 { get; set; }
        public string SiyoStaYmd { get; set; }
        public string SiyoEndYmd { get; set; }
        public string UpdYmd { get; set; }
        public string UpdTime { get; set; }
        public int UpdSyainCd { get; set; }
        public string UpdPrgId { get; set; }
    }
}