// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HassyaAllrightCloud.Domain.Entities
{
    public partial class VpmRyokin
    {
        public byte RyokinTikuCd { get; set; }
        public string RyokinCd { get; set; }
        public byte RoadCorporationKbn { get; set; }
        public string RoadCorporationName { get; set; }
        public string DouroName { get; set; }
        public string RyokinNm { get; set; }
        public string RyakuNm { get; set; }
        public string SiyoStaYmd { get; set; }
        public string SiyoEndYmd { get; set; }
        public string UpdYmd { get; set; }
        public string UpdTime { get; set; }
        public int UpdSyainCd { get; set; }
        public string UpdPrgId { get; set; }
    }
}