// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HassyaAllrightCloud.Domain.Entities
{
    public partial class VpmSyain
    {
        public int SyainCdSeq { get; set; }
        public string SyainCd { get; set; }
        public string Kana { get; set; }
        public string SyainNm { get; set; }
        public string KariSyainNm { get; set; }
        public string NyusyaYmd { get; set; }
        public string TaisyaYmd { get; set; }
        public string BirthYmd { get; set; }
        public byte Seibetsu { get; set; }
        public string ZipCd { get; set; }
        public string Jyus1 { get; set; }
        public string Jyus2 { get; set; }
        public string ApaManNm { get; set; }
        public string TelNo { get; set; }
        public string KeitaiNo { get; set; }
        public string MailAdd1 { get; set; }
        public string MailAdd2 { get; set; }
        public string MenkyoNo { get; set; }
        public string ExpItem { get; set; }
        public string UpdYmd { get; set; }
        public string UpdTime { get; set; }
        public int UpdSyainCd { get; set; }
        public string UpdPrgId { get; set; }
    }
}