// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HassyaAllrightCloud.Domain.Entities
{
    public partial class VpmSeisan
    {
        public int TenantCdSeq { get; set; }
        public int SeisanCdSeq { get; set; }
        public short SeisanCd { get; set; }
        public string SeisanNm { get; set; }
        public string RyakuNm { get; set; }
        public byte SeisanKbn { get; set; }
        public byte SiyoKbn { get; set; }
        public string UpdYmd { get; set; }
        public string UpdTime { get; set; }
        public int UpdSyainCd { get; set; }
        public string UpdPrgId { get; set; }
    }
}