// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HassyaAllrightCloud.Domain.Entities
{
    public partial class VpmSyaRyo
    {
        public int SyaRyoCdSeq { get; set; }
        public int SyaRyoCd { get; set; }
        public byte NinkaKbn { get; set; }
        public int SyaSyuCdSeq { get; set; }
        public string Kana { get; set; }
        public string SyaRyoNm { get; set; }
        public string KariSyaRyoNm { get; set; }
        public int SyainCdSeq { get; set; }
        public byte TeiCnt { get; set; }
        public byte HojoCnt { get; set; }
        public int NenryoCd1Seq { get; set; }
        public int NenryoCd2Seq { get; set; }
        public int NenryoCd3Seq { get; set; }
        public string UpdYmd { get; set; }
        public string UpdTime { get; set; }
        public int UpdSyainCd { get; set; }
        public string UpdPrgId { get; set; }
    }
}