// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HassyaAllrightCloud.Domain.Entities
{
    public partial class VpmSyuTaikinCalculationTime
    {
        public int CompanyCdSeq { get; set; }
        public byte SyugyoKbn { get; set; }
        public byte KouZokPtnKbn { get; set; }
        public int SyukinCalculationTimeMinutes { get; set; }
        public int TaikinCalculationTimeMinutes { get; set; }
        public string UpdYmd { get; set; }
        public string UpdTime { get; set; }
        public int UpdSyainCd { get; set; }
        public string UpdPrgId { get; set; }
    }
}