// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HassyaAllrightCloud.Domain.Entities
{
    public partial class VpmTokisk
    {
        public int TenantCdSeq { get; set; }
        public int TokuiSeq { get; set; }
        public int GyosyaCdSeq { get; set; }
        public short TokuiCd { get; set; }
        public string Kana { get; set; }
        public string TokuiNm { get; set; }
        public string RyakuNm { get; set; }
        public string SiyoStaYmd { get; set; }
        public string SiyoEndYmd { get; set; }
        public string UpdYmd { get; set; }
        public string UpdTime { get; set; }
        public int UpdSyainCd { get; set; }
        public string UpdPrgId { get; set; }
    }
}