// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HassyaAllrightCloud.Domain.Entities
{
    public partial class VpmTokiSt
    {
        public int TokuiSeq { get; set; }
        public int SitenCdSeq { get; set; }
        public short SitenCd { get; set; }
        public int SeiCdSeq { get; set; }
        public int SeiSitenCdSeq { get; set; }
        public string Kana { get; set; }
        public string SitenNm { get; set; }
        public string RyakuNm { get; set; }
        public string ZipCd { get; set; }
        public string Jyus1 { get; set; }
        public string Jyus2 { get; set; }
        public string TelNo { get; set; }
        public string FaxNo { get; set; }
        public string TokuiTanNm { get; set; }
        public string TokuiMail { get; set; }
        public byte SimeD { get; set; }
        public decimal TesuRitu { get; set; }
        public byte TesKbn { get; set; }
        public decimal TesuRituFut { get; set; }
        public byte TesKbnFut { get; set; }
        public decimal TesuRituGui { get; set; }
        public byte TesKbnGui { get; set; }
        public byte NyuKesiKbn { get; set; }
        public byte SeiPrnKbn { get; set; }
        public byte SeiKurKbn { get; set; }
        public byte SeiMaeOflg { get; set; }
        public string SihBankCd { get; set; }
        public string SihBankSitCd { get; set; }
        public byte SihYokinSyu { get; set; }
        public string SihKouzaNo { get; set; }
        public byte SihDd { get; set; }
        public short SihSit { get; set; }
        public string SiyoStaYmd { get; set; }
        public string SiyoEndYmd { get; set; }
        public string UpdYmd { get; set; }
        public string UpdTime { get; set; }
        public int UpdSyainCd { get; set; }
        public string UpdPrgId { get; set; }
        public int TesuShihKbn { get; set; }
    }
}