// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HassyaAllrightCloud.Domain.Entities
{
    public partial class VpmTransportationFeeRule
    {
        public int TransportationPlaceCodeSeq { get; set; }
        public string StartYmd { get; set; }
        public string EndYmd { get; set; }
        public int TransportationPlaceCode { get; set; }
        public string TransportationPlaceName { get; set; }
        public int BigVehicalMaxUnitPriceforKm { get; set; }
        public int BigVehicalMinUnitPriceforKm { get; set; }
        public int MedVehicalMaxUnitPriceforKm { get; set; }
        public int MedVehicalMinUnitPriceforKm { get; set; }
        public int SmallVehicalMaxUnitPriceforKm { get; set; }
        public int SmallVehicalMinUnitPriceforKm { get; set; }
        public int BigVehicalMaxUnitPriceforHour { get; set; }
        public int BigVehicalMinUnitPriceforHour { get; set; }
        public int MedVehicalMaxUnitPriceforHour { get; set; }
        public int MedVehicalMinUnitPriceforHour { get; set; }
        public int SmallVehicalMaxUnitPriceforHour { get; set; }
        public int SmallVehicalMinUnitPriceforHour { get; set; }
        public int ChangeDriverMaxUnitPriceforKm { get; set; }
        public int ChangeDriverMinUnitPriceforKm { get; set; }
        public int ChangeDriverMaxUnitPriceforHour { get; set; }
        public int ChangeDriverMinUnitPriceforHour { get; set; }
        public short RunningMid9MaxRate { get; set; }
        public short RunningMid9MinRate { get; set; }
        public short SpecialVehicalMaxRate { get; set; }
        public short SpecialVehicalMinRate { get; set; }
        public string UpdYmd { get; set; }
        public string UpdTime { get; set; }
        public int UpdSyainCd { get; set; }
        public string UpdPrgId { get; set; }
    }
}