// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HassyaAllrightCloud.Domain.Entities
{
    public partial class VpmTenantGroupDetail
    {
        public int TenantGroupCdSeq { get; set; }
        public int TenantCdSeq { get; set; }
        public string StaYmd { get; set; }
        public string EndYmd { get; set; }
        public byte SiyoKbn { get; set; }
        public string UpdYmd { get; set; }
        public string UpdTime { get; set; }
        public int UpdSyainCd { get; set; }
        public string UpdPrgId { get; set; }
    }
}