// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HassyaAllrightCloud.Domain.Entities
{
    public partial class VpmTenant
    {
        public int TenantCdSeq { get; set; }
        public string TenantCd { get; set; }
        public string TenantCompanyName { get; set; }
        public string MailAddress { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string TellNumber { get; set; }
        public string FaxNumber { get; set; }
        public int SalesRepresentativeCdSeq { get; set; }
        public int SystemRepresentative1CdSeq { get; set; }
        public int SystemRepresentative2CdSeq { get; set; }
        public string Customer1 { get; set; }
        public string Customer2 { get; set; }
        public string Remarks { get; set; }
        public string StaYmd { get; set; }
        public string EndYmd { get; set; }
        public byte SiyoKbn { get; set; }
        public string UpdYmd { get; set; }
        public string UpdTime { get; set; }
        public int UpdSyainCd { get; set; }
        public string UpdPrgId { get; set; }
    }
}