// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HassyaAllrightCloud.Domain.Entities
{
    public partial class VpmUserSetItm
    {
        public int ItemSeq { get; set; }
        public string ItemType { get; set; }
        public string ItemCd { get; set; }
        public string ItemNm { get; set; }
        public byte SeiKbn { get; set; }
        public string DefaultVal { get; set; }
        public string UpdYmd { get; set; }
        public string UpdTime { get; set; }
        public int UpdSyainCd { get; set; }
        public string UpdPrgId { get; set; }
    }
}