// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HassyaAllrightCloud.Domain.Entities
{
    public partial class VpmYoyKbn
    {
        public int TenantCdSeq { get; set; }
        public int YoyaKbnSeq { get; set; }
        public byte YoyaKbn { get; set; }
        public string YoyaKbnNm { get; set; }
        public byte Yoyagamsyu { get; set; }
        public byte UnsouKbn { get; set; }
        public byte SiyoKbn { get; set; }
        public string UpdYmd { get; set; }
        public string UpdTime { get; set; }
        public int UpdSyainCd { get; set; }
        public string UpdPrgId { get; set; }
    }
}