USE [HOC_Kashikiri]
GO

/****** Object:  Index [NonClusteredIndex-20210520-103035]    Script Date: 5/20/2021 10:31:47 AM ******/
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20210520-103035] ON [dbo].[TKD_SeiPrS]
(
	[SeiOutSeq] ASC
)
INCLUDE([SeiHatYmd]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


