USE [HOC_Kashikiri]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [NonClusteredIndex-20210329-144341]    Script Date: 3/29/2021 2:58:26 PM ******/
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20210329-144341] ON [dbo].[TKD_Unkobi]
(
	[UkeNo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


