using MediatR;
using System.Collections.Generic;
using System.Threading.Tasks;
using HassyaAllrightCloud.Domain.Dto;
using System.Threading;
using HassyaAllrightCloud.Infrastructure.Persistence;
using StoredProcedureEFCore;
using HassyaAllrightCloud.Domain.Dto.RegulationSetting;
using System.Linq;

namespace HassyaAllrightCloud.Application.RegulationSetting.Queries
{
    public class GetRegulationSettings : IRequest<List<SPModel>>
    {
        public RegulationSettingModel model { get; set; }
        public class Handler : IRequestHandler<GetRegulationSettings, List<SPModel>>
        {
            private readonly KobodbContext _context;
            public Handler(KobodbContext context)
            {
                _context = context;
            }
            public async Task<List<SPModel>> Handle(GetRegulationSettings request, CancellationToken cancellationToken)
            {
                var result = new List<SPModel>();

                var kashikiriSetting = new List<KashikiriSettingData>();
                await _context.LoadStoredProc("PK_dGetKashikiriSetting_R")
                    .AddParam("@CompanyFrom", request.model.CompanyFrom?.CompanyCd ?? 0)
                    .AddParam("@CompanyTo", request.model.CompanyTo?.CompanyCd ?? 0)
                    .AddParam("@TenantCdSeq", new ClaimModel().TenantID)
                    .ExecAsync(async es => kashikiriSetting = await es.ToListAsync<KashikiriSettingData>(), cancellationToken);

                var codeKbnSetting = new List<DataSettingFromCodeKbn>();
                await _context.LoadStoredProc("PK_dGetCodeKbnSetting_R")
                    .AddParam("@TenantCdSeq", new ClaimModel().TenantID)
                    .ExecAsync(async es => codeKbnSetting = await es.ToListAsync<DataSettingFromCodeKbn>(), cancellationToken);

                foreach(var item in kashikiriSetting)
                {
                    result.Add(new SPModel()
                    {
                        AutKarJyun = item.AutKarJyun,
                        AutKouKbn = item.AutKouKbn,
                        CanEKan1 = item.CanEkan1,
                        CanEKan2 = item.CanEkan2,
                        CanEKan3 = item.CanEkan3,
                        CanEKan4 = item.CanEkan4,
                        CanEKan5 = item.CanEkan5,
                        CanEKan6 = item.CanEkan6,
                        CanJidoKbn = item.CanJidoKbn,
                        CanKbn = item.CanKbn,
                        CanKikan = item.CanKikan,
                        CanMDKbn = item.CanMdkbn,
                        CanRit1 = item.CanRit1,
                        CanRit2 = item.CanRit2,
                        CanRit3 = item.CanRit3,
                        CanRit4 = item.CanRit4,
                        CanRit5 = item.CanRit5,
                        CanRit6 = item.CanRit6,
                        CanSKan1 = item.CanSkan1,
                        CanSKan2 = item.CanSkan2,
                        CanSKan3 = item.CanSkan3,
                        CanSKan4 = item.CanSkan4,
                        CanSKan5 = item.CanSkan5,
                        CanSKan6 = item.CanSkan6,
                        CanWaitKbn = item.CanWaitKbn,
                        ColHai = item.ColHai,
                        ColHaiin = item.ColHaiin,
                        ColIcHai = item.ColIcHai,
                        ColIcHaiin = item.ColIcHaiin,
                        ColIcKari = item.ColIcKari,
                        ColIcKariH = item.ColIcKariH,
                        ColIcNCou = item.ColIcNcou,
                        ColIcNip = item.ColIcNip,
                        ColIcNyu = item.ColIcNyu,
                        ColIcShiha = item.ColIcShiha,
                        ColIcSCou = item.ColIcScou,
                        ColIcWari = item.ColIcWari,
                        ColIcYou = item.ColIcYou,
                        ColKahar = item.ColKahar,
                        ColKaku = item.ColKaku,
                        ColKanyu = item.ColKanyu,
                        ColKari = item.ColKari,
                        ColKariH = item.ColKariH,
                        ColKYoy = item.ColKyoy,
                        ColMiKari = item.ColMiKari,
                        ColNCou = item.ColNcou,
                        ColNin = item.ColNin,
                        ColNip = item.ColNip,
                        ColNyu = item.ColNyu,
                        ColSCou = item.ColScou,
                        ColSelect = item.ColSelect,
                        ColShiha = item.ColShiha,
                        ColWari = item.ColWari,
                        ColYou = item.ColYou,
                        CompanyCdSeq = item.CompanyCdSeq,
                        DaySyoKbn = item.DaySyoKbn,
                        DrvAutoSet = item.DrvAutoSet,
                        ETCKinKbn = item.EtckinKbn,
                        ExpItem = item.ExpItem,
                        FutaiCopyFlg = item.FutaiCopyFlg,
                        FutSF1Flg = item.FutSf1flg,
                        FutSF2Flg = item.FutSf2flg,
                        FutSF3Flg = item.FutSf3flg,
                        FutSF4Flg = item.FutSf4flg,
                        FutTumCdSeq = item.FutTumCdSeq,
                        GetSyoKbn = item.GetSyoKbn,
                        GoSyaAutoSet = item.GoSyaAutoSet,
                        GuiAutoSet = item.GuiAutoSet,
                        GuideFutTumCdSeq = item.GuideFutTumCdSeq,
                        HoukoKbn = item.HoukoKbn,
                        HouOutKbn = item.HouOutKbn,
                        HouZeiKbn = item.HouZeiKbn,
                        JisKinKyuNm01 = item.JisKinKyuNm01,
                        JisKinKyuNm02 = item.JisKinKyuNm02,
                        JisKinKyuNm03 = item.JisKinKyuNm03,
                        JisKinKyuNm04 = item.JisKinKyuNm04,
                        JisKinKyuNm05 = item.JisKinKyuNm05,
                        JisKinKyuNm06 = item.JisKinKyuNm06,
                        JisKinKyuNm07 = item.JisKinKyuNm07,
                        JisKinKyuNm08 = item.JisKinKyuNm08,
                        JisKinKyuNm09 = item.JisKinKyuNm09,
                        JisKinKyuNm10 = item.JisKinKyuNm10,
                        JKariKbn = item.JkariKbn,
                        JKBunPat = item.JkbunPat,
                        JoshaCopyFlg = item.JoshaCopyFlg,
                        JymAChkKbn = item.JymAchkKbn,
                        JyoSenInfoPtnCol1 = item.JyoSenInfoPtnCol1,
                        JyoSenInfoPtnCol10 = item.JyoSenInfoPtnCol10,
                        JyoSenInfoPtnCol11 = item.JyoSenInfoPtnCol11,
                        JyoSenInfoPtnCol12 = item.JyoSenInfoPtnCol12,
                        JyoSenInfoPtnCol13 = item.JyoSenInfoPtnCol13,
                        JyoSenInfoPtnCol14 = item.JyoSenInfoPtnCol14,
                        JyoSenInfoPtnCol15 = item.JyoSenInfoPtnCol15,
                        JyoSenInfoPtnCol2 = item.JyoSenInfoPtnCol2,
                        JyoSenInfoPtnCol3 = item.JyoSenInfoPtnCol3,
                        JyoSenInfoPtnCol4 = item.JyoSenInfoPtnCol4,
                        JyoSenInfoPtnCol5 = item.JyoSenInfoPtnCol5,
                        JyoSenInfoPtnCol6 = item.JyoSenInfoPtnCol6,
                        JyoSenInfoPtnCol7 = item.JyoSenInfoPtnCol7,
                        JyoSenInfoPtnCol8 = item.JyoSenInfoPtnCol8,
                        JyoSenInfoPtnCol9 = item.JyoSenInfoPtnCol9,
                        JyoSenInfoPtnKbn1 = item.JyoSenInfoPtnKbn1,
                        JyoSenInfoPtnKbn10 = item.JyoSenInfoPtnKbn10,
                        JyoSenInfoPtnKbn11 = item.JyoSenInfoPtnKbn11,
                        JyoSenInfoPtnKbn12 = item.JyoSenInfoPtnKbn12,
                        JyoSenInfoPtnKbn13 = item.JyoSenInfoPtnKbn13,
                        JyoSenInfoPtnKbn14 = item.JyoSenInfoPtnKbn14,
                        JyoSenInfoPtnKbn15 = item.JyoSenInfoPtnKbn15,
                        JyoSenInfoPtnKbn2 = item.JyoSenInfoPtnKbn2,
                        JyoSenInfoPtnKbn3 = item.JyoSenInfoPtnKbn3,
                        JyoSenInfoPtnKbn4 = item.JyoSenInfoPtnKbn4,
                        JyoSenInfoPtnKbn5 = item.JyoSenInfoPtnKbn5,
                        JyoSenInfoPtnKbn6 = item.JyoSenInfoPtnKbn6,
                        JyoSenInfoPtnKbn7 = item.JyoSenInfoPtnKbn7,
                        JyoSenInfoPtnKbn8 = item.JyoSenInfoPtnKbn8,
                        JyoSenInfoPtnKbn9 = item.JyoSenInfoPtnKbn9,
                        JyoSenMjPtnCol1 = item.JyoSenMjPtnCol1,
                        JyoSenMjPtnCol2 = item.JyoSenMjPtnCol2,
                        JyoSenMjPtnCol3 = item.JyoSenMjPtnCol3,
                        JyoSenMjPtnCol4 = item.JyoSenMjPtnCol4,
                        JyoSenMjPtnCol5 = item.JyoSenMjPtnCol5,
                        JyoSenMjPtnKbn1 = item.JyoSenMjPtnKbn1,
                        JyoSenMjPtnKbn2 = item.JyoSenMjPtnKbn2,
                        JyoSenMjPtnKbn3 = item.JyoSenMjPtnKbn3,
                        JyoSenMjPtnKbn4 = item.JyoSenMjPtnKbn4,
                        JyoSenMjPtnKbn5 = item.JyoSenMjPtnKbn5,
                        JyoSyaChkSiyoKbn = item.JyoSyaChkSiyoKbn,
                        KarSyuKiTimeSiyoKbn = item.KarSyuKiTimeSiyoKbn,
                        KoteiCopyFlg = item.KoteiCopyFlg,
                        KouYouSet = item.KouYouSet,
                        MeiShyKbn = item.MeiShyKbn,
                        QuotationTransfer = item.QuotationTransfer,
                        SeiCom1 = item.SeiCom1,
                        SeiCom2 = item.SeiCom2,
                        SeiCom3 = item.SeiCom3,
                        SeiCom4 = item.SeiCom4,
                        SeiCom5 = item.SeiCom5,
                        SeiCom6 = item.SeiCom6,
                        SeiGenFlg = item.SeiGenFlg,
                        SeiKrksKbn = item.SeiKrksKbn,
                        SeiMuki = item.SeiMuki,
                        SeisanCdSeq = item.SeisanCdSeq,
                        SenBackPtnCol = item.SenBackPtnCol,
                        SenBackPtnKbn = item.SenBackPtnKbn,
                        SenDayRenge = item.SenDayRenge,
                        SenDefWidth = item.SenDefWidth,
                        SenHyoHi = item.SenHyoHi,
                        SenMikDefFlg = item.SenMikDefFlg,
                        SenOBPtnCol = item.SenObptnCol,
                        SenOBPtnKbn = item.SenObptnKbn,
                        SenYouDefFlg = item.SenYouDefFlg,
                        SokoJunKbn = item.SokoJunKbn,
                        SryHyjHga = item.SryHyjHga,
                        SryHyjSyu = item.SryHyjSyu,
                        SryHyjTch = item.SryHyjTch,
                        SryHyjTde = item.SryHyjTde,
                        SryHyjTka = item.SryHyjTka,
                        SyaIrePat = item.SyaIrePat,
                        SyaSenInfoPtnCol1 = item.SyaSenInfoPtnCol1,
                        SyaSenInfoPtnCol10 = item.SyaSenInfoPtnCol10,
                        SyaSenInfoPtnCol11 = item.SyaSenInfoPtnCol11,
                        SyaSenInfoPtnCol12 = item.SyaSenInfoPtnCol12,
                        SyaSenInfoPtnCol13 = item.SyaSenInfoPtnCol13,
                        SyaSenInfoPtnCol14 = item.SyaSenInfoPtnCol14,
                        SyaSenInfoPtnCol15 = item.SyaSenInfoPtnCol15,
                        SyaSenInfoPtnCol2 = item.SyaSenInfoPtnCol2,
                        SyaSenInfoPtnCol3 = item.SyaSenInfoPtnCol3,
                        SyaSenInfoPtnCol4 = item.SyaSenInfoPtnCol4,
                        SyaSenInfoPtnCol5 = item.SyaSenInfoPtnCol5,
                        SyaSenInfoPtnCol6 = item.SyaSenInfoPtnCol6,
                        SyaSenInfoPtnCol7 = item.SyaSenInfoPtnCol7,
                        SyaSenInfoPtnCol8 = item.SyaSenInfoPtnCol8,
                        SyaSenInfoPtnCol9 = item.SyaSenInfoPtnCol9,
                        SyaSenInfoPtnKbn1 = item.SyaSenInfoPtnKbn1,
                        SyaSenInfoPtnKbn10 = item.SyaSenInfoPtnKbn10,
                        SyaSenInfoPtnKbn11 = item.SyaSenInfoPtnKbn11,
                        SyaSenInfoPtnKbn12 = item.SyaSenInfoPtnKbn12,
                        SyaSenInfoPtnKbn13 = item.SyaSenInfoPtnKbn13,
                        SyaSenInfoPtnKbn14 = item.SyaSenInfoPtnKbn14,
                        SyaSenInfoPtnKbn15 = item.SyaSenInfoPtnKbn15,
                        SyaSenInfoPtnKbn2 = item.SyaSenInfoPtnKbn2,
                        SyaSenInfoPtnKbn3 = item.SyaSenInfoPtnKbn3,
                        SyaSenInfoPtnKbn4 = item.SyaSenInfoPtnKbn4,
                        SyaSenInfoPtnKbn5 = item.SyaSenInfoPtnKbn5,
                        SyaSenInfoPtnKbn6 = item.SyaSenInfoPtnKbn6,
                        SyaSenInfoPtnKbn7 = item.SyaSenInfoPtnKbn7,
                        SyaSenInfoPtnKbn8 = item.SyaSenInfoPtnKbn8,
                        SyaSenInfoPtnKbn9 = item.SyaSenInfoPtnKbn9,
                        SyaSenMjPtnCol1 = item.SyaSenMjPtnCol1,
                        SyaSenMjPtnCol2 = item.SyaSenMjPtnCol2,
                        SyaSenMjPtnCol3 = item.SyaSenMjPtnCol3,
                        SyaSenMjPtnCol4 = item.SyaSenMjPtnCol4,
                        SyaSenMjPtnCol5 = item.SyaSenMjPtnCol5,
                        SyaSenMjPtnKbn1 = item.SyaSenMjPtnKbn1,
                        SyaSenMjPtnKbn2 = item.SyaSenMjPtnKbn2,
                        SyaSenMjPtnKbn3 = item.SyaSenMjPtnKbn3,
                        SyaSenMjPtnKbn4 = item.SyaSenMjPtnKbn4,
                        SyaSenMjPtnKbn5 = item.SyaSenMjPtnKbn5,
                        SyaUntKbn = item.SyaUntKbn,
                        SyohiHasu = item.SyohiHasu,
                        TehaiAutoSet = item.TehaiAutoSet,
                        TehaiCopyFlg = item.TehaiCopyFlg,
                        TesuHasu = item.TesuHasu,
                        TumiCopyFlg = item.TumiCopyFlg,
                        UkbCopyFlg = item.UkbCopyFlg,
                        UntZeiKbn = item.UntZeiKbn,
                        UpdPrgID = item.UpdPrgId,
                        UpdSyainCd = item.UpdSyainCd,
                        UpdTime = item.UpdTime,
                        UpdYmd = item.UpdYmd,
                        UriHenKbn = item.UriHenKbn,
                        UriHenKikan = item.UriHenKikan,
                        UriKbn = item.UriKbn,
                        UriMDKbn = item.UriMdkbn,
                        UriZeroChk = item.UriZeroChk,
                        YouSagaKbn = item.YouSagaKbn,
                        YouTesuKbn = item.YouTesuKbn,
                        YoySyuKiTimeSiyoKbn = item.YoySyuKiTimeSiyoKbn,
                        YykCopyFlg = item.YykCopyFlg,
                        YykHaiSTime = item.YykHaiStime,
                        YykTouTime = item.YykTouTime,
                        ZasyuKbn = item.ZasyuKbn,
                        TumZeiKbn = item.TumZeiKbn,

                        CompanyCdSeqCompanyCd = item.CompanyCdSeqCompanyCd,
                        CompanyCdSeqCompanyNm = item.CompanyCdSeqCompanyNm,
                        CompanyCdSeqRyakuNm = item.CompanyCdSeqRyakuNm,
                        SyainCd = item.SyainCd,
                        SyainNm = item.SyainNm,

                        UriKbnCodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "URIKBN" && int.Parse(x.CodeKbn) == item.UriKbn).FirstOrDefault()?.CodeKbnNm,
                        SyohiHasuCodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "SYOHIHASU" && int.Parse(x.CodeKbn) == item.SyohiHasu).FirstOrDefault()?.CodeKbnNm,
                        TesuHasuCodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "TESUHASU" && int.Parse(x.CodeKbn) == item.TesuHasu).FirstOrDefault()?.CodeKbnNm,
                        HoukoKbnCodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "HOUKOKBN" && int.Parse(x.CodeKbn) == item.HoukoKbn).FirstOrDefault()?.CodeKbnNm,
                        HouZeiKbnCodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "HOUZEIKBN" && int.Parse(x.CodeKbn) == item.HouZeiKbn).FirstOrDefault()?.CodeKbnNm,
                        JKariKbnCodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "JKARIKBN" && int.Parse(x.CodeKbn) == item.JkariKbn).FirstOrDefault()?.CodeKbnNm,
                        AutKarJyunCodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "AUTKARJYUN" && int.Parse(x.CodeKbn) == item.AutKarJyun).FirstOrDefault()?.CodeKbnNm,
                        JKBunPatCodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "JKBUNPAT" && int.Parse(x.CodeKbn) == item.JkbunPat).FirstOrDefault()?.CodeKbnNm,
                        SyaIrePatCodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "SYAIREPAT" && int.Parse(x.CodeKbn) == item.SyaIrePat).FirstOrDefault()?.CodeKbnNm,
                        JymAChkKbnCodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "JYMACHKKBN" && int.Parse(x.CodeKbn) == item.JymAchkKbn).FirstOrDefault()?.CodeKbnNm,
                        UriHenKbnCodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "URIHENKBN" && int.Parse(x.CodeKbn) == item.UriHenKbn).FirstOrDefault()?.CodeKbnNm,
                        UriMDKbnCodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "URIMDKBN" && int.Parse(x.CodeKbn) == item.UriMdkbn).FirstOrDefault()?.CodeKbnNm,
                        UriZeroChkCodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "URIZEROCHK" && int.Parse(x.CodeKbn) == item.UriZeroChk).FirstOrDefault()?.CodeKbnNm,


                        CanKbnCodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "CANKBN" && int.Parse(x.CodeKbn) == item.CanKbn).FirstOrDefault()?.CodeKbnNm,
                        CanMDKbnCodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "CANMDKBN" && int.Parse(x.CodeKbn) == item.CanMdkbn).FirstOrDefault()?.CodeKbnNm,
                        CanWaitKbnCodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "CANWAITKBN" && int.Parse(x.CodeKbn) == item.CanWaitKbn).FirstOrDefault()?.CodeKbnNm,
                        CanJidoKbnCodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "CANJIDOKBN" && int.Parse(x.CodeKbn) == item.CanJidoKbn).FirstOrDefault()?.CodeKbnNm,
                        YouTesuKbnCodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "YOUTESUKBN" && int.Parse(x.CodeKbn) == item.YouTesuKbn).FirstOrDefault()?.CodeKbnNm,

                        YouSagaKbnCodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "YOUSAGAKBN" && int.Parse(x.CodeKbn) == item.YouSagaKbn).FirstOrDefault()?.CodeKbnNm,
                        SyaUntKbnCodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "SYAUNTKBN" && int.Parse(x.CodeKbn) == item.SyaUntKbn).FirstOrDefault()?.CodeKbnNm,
                        ZasyuKbnCodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "ZASYUKBN" && int.Parse(x.CodeKbn) == item.ZasyuKbn).FirstOrDefault()?.CodeKbnNm,
                        FutSF1FlgCodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "FUTSF1FLG" && int.Parse(x.CodeKbn) == item.FutSf1flg).FirstOrDefault()?.CodeKbnNm,
                        FutSF2FlgCodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "FUTSF2FLG" && int.Parse(x.CodeKbn) == item.FutSf2flg).FirstOrDefault()?.CodeKbnNm,
                        FutSF3FlgCodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "FUTSF3FLG" && int.Parse(x.CodeKbn) == item.FutSf3flg).FirstOrDefault()?.CodeKbnNm,
                        FutSF4FlgCodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "FUTSF4FLG" && int.Parse(x.CodeKbn) == item.FutSf4flg).FirstOrDefault()?.CodeKbnNm,

                        SokoJunKbnCodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "SOKOJUNKBN" && int.Parse(x.CodeKbn) == item.SokoJunKbn).FirstOrDefault()?.CodeKbnNm,
                        UntZeiKbnCodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "UNTZEIKBN" && int.Parse(x.CodeKbn) == item.UntZeiKbn).FirstOrDefault()?.CodeKbnNm,
                        TumZeiKbnCodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "TUMZEIKBN" && int.Parse(x.CodeKbn) == item.TumZeiKbn).FirstOrDefault()?.CodeKbnNm,
                        GetSyoKbnCodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "GETSYOKBN" && int.Parse(x.CodeKbn) == item.GetSyoKbn).FirstOrDefault()?.CodeKbnNm,
                        SeiKrksKbnCodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "SEIKRKSKBN" && int.Parse(x.CodeKbn) == item.SeiKrksKbn).FirstOrDefault()?.CodeKbnNm,
                        DaySyoKbnCodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "DAYSYOKBN" && int.Parse(x.CodeKbn) == item.DaySyoKbn).FirstOrDefault()?.CodeKbnNm,
                        KouYouSetCodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "KOUYOUSET" && int.Parse(x.CodeKbn) == item.KouYouSet).FirstOrDefault()?.CodeKbnNm,
                        AutKouKbnCodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "AUTKOUKBN" && int.Parse(x.CodeKbn) == item.AutKouKbn).FirstOrDefault()?.CodeKbnNm,
                        SenYouDefFlgCodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "SENYOUDEFFLG" && int.Parse(x.CodeKbn) == item.SenYouDefFlg).FirstOrDefault()?.CodeKbnNm,
                        SenMikDefFlgCodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "SENMIKDEFFLG" && int.Parse(x.CodeKbn) == item.SenMikDefFlg).FirstOrDefault()?.CodeKbnNm,
                        KoteiCopyFlgCodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "COPYFLG" && int.Parse(x.CodeKbn) == item.KoteiCopyFlg).FirstOrDefault()?.CodeKbnNm,
                        FutaiCopyFlgCodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "COPYFLG" && int.Parse(x.CodeKbn) == item.FutaiCopyFlg).FirstOrDefault()?.CodeKbnNm,
                        TumiCopyFlgCodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "COPYFLG" && int.Parse(x.CodeKbn) == item.TumiCopyFlg).FirstOrDefault()?.CodeKbnNm,
                        TehaiCopyFlgCodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "COPYFLG" && int.Parse(x.CodeKbn) == item.TehaiCopyFlg).FirstOrDefault()?.CodeKbnNm,
                        JoshaCopyFlgCodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "COPYFLG" && int.Parse(x.CodeKbn) == item.JoshaCopyFlg).FirstOrDefault()?.CodeKbnNm,
                        YykCopyFlgCodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "COPYFLG" && int.Parse(x.CodeKbn) == item.YykCopyFlg).FirstOrDefault()?.CodeKbnNm,
                        UkbCopyFlgCodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "COPYFLG" && int.Parse(x.CodeKbn) == item.UkbCopyFlg).FirstOrDefault()?.CodeKbnNm,
                        QuotationTransferCodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "COPYFLG" && int.Parse(x.CodeKbn) == item.QuotationTransfer).FirstOrDefault()?.CodeKbnNm,

                        SeiGenFlgCodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "SEIGENFLG" && int.Parse(x.CodeKbn) == item.SeiGenFlg).FirstOrDefault()?.CodeKbnNm,
                        HouOutKbnCodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "HOUOUTKBN" && int.Parse(x.CodeKbn) == item.HouOutKbn).FirstOrDefault()?.CodeKbnNm,
                        MeiShyKbnCodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "MEISHYKBN" && int.Parse(x.CodeKbn) == item.MeiShyKbn).FirstOrDefault()?.CodeKbnNm,
                        SyaSenMjPtnKbn1CodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "SENMJPTNKBN" && int.Parse(x.CodeKbn) == item.SyaSenMjPtnKbn1).FirstOrDefault()?.CodeKbnNm,
                        SyaSenMjPtnKbn2CodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "SENMJPTNKBN" && int.Parse(x.CodeKbn) == item.SyaSenMjPtnKbn2).FirstOrDefault()?.CodeKbnNm,
                        SyaSenMjPtnKbn3CodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "SENMJPTNKBN" && int.Parse(x.CodeKbn) == item.SyaSenMjPtnKbn3).FirstOrDefault()?.CodeKbnNm,
                        SyaSenMjPtnKbn4CodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "SENMJPTNKBN" && int.Parse(x.CodeKbn) == item.SyaSenMjPtnKbn4).FirstOrDefault()?.CodeKbnNm,
                        SyaSenMjPtnKbn5CodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "SENMJPTNKBN" && int.Parse(x.CodeKbn) == item.SyaSenMjPtnKbn5).FirstOrDefault()?.CodeKbnNm,
                        JyoSenMjPtnKbn1CodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "SENMJPTNKBN" && int.Parse(x.CodeKbn) == item.JyoSenMjPtnKbn1).FirstOrDefault()?.CodeKbnNm,
                        JyoSenMjPtnKbn2CodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "SENMJPTNKBN" && int.Parse(x.CodeKbn) == item.JyoSenMjPtnKbn2).FirstOrDefault()?.CodeKbnNm,
                        JyoSenMjPtnKbn3CodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "SENMJPTNKBN" && int.Parse(x.CodeKbn) == item.JyoSenMjPtnKbn3).FirstOrDefault()?.CodeKbnNm,
                        JyoSenMjPtnKbn4CodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "SENMJPTNKBN" && int.Parse(x.CodeKbn) == item.JyoSenMjPtnKbn4).FirstOrDefault()?.CodeKbnNm,
                        JyoSenMjPtnKbn5CodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "SENMJPTNKBN" && int.Parse(x.CodeKbn) == item.JyoSenMjPtnKbn5).FirstOrDefault()?.CodeKbnNm,


                        JyoSyaChkSiyoKbnCodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "SIYOKBN" && int.Parse(x.CodeKbn) == item.JyoSyaChkSiyoKbn).FirstOrDefault()?.CodeKbnNm,
                        GuiAutoSetCodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "SIYOKBN" && int.Parse(x.CodeKbn) == item.GuiAutoSet).FirstOrDefault()?.CodeKbnNm,
                        DrvAutoSetCodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "SIYOKBN" && int.Parse(x.CodeKbn) == item.DrvAutoSet).FirstOrDefault()?.CodeKbnNm,
                        SenOBPtnKbnCodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "SIYOKBN" && int.Parse(x.CodeKbn) == item.SenObptnKbn).FirstOrDefault()?.CodeKbnNm,
                        SenBackPtnKbnCodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "SIYOKBN" && int.Parse(x.CodeKbn) == item.SenBackPtnKbn).FirstOrDefault()?.CodeKbnNm,
                        TehaiAutoSetCodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "SIYOKBN" && int.Parse(x.CodeKbn) == item.TehaiAutoSet).FirstOrDefault()?.CodeKbnNm,
                        GoSyaAutoSetCodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "SIYOKBN" && int.Parse(x.CodeKbn) == item.GoSyaAutoSet).FirstOrDefault()?.CodeKbnNm,
                        YoySyuKiTimeSiyoKbnCodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "SIYOKBN" && int.Parse(x.CodeKbn) == item.YoySyuKiTimeSiyoKbn).FirstOrDefault()?.CodeKbnNm,
                        KarSyuKiTimeSiyoKbnCodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "SIYOKBN" && int.Parse(x.CodeKbn) == item.KarSyuKiTimeSiyoKbn).FirstOrDefault()?.CodeKbnNm,

                        SyaSenInfoPtnKbn1CodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "SENMJPTNKBN" && int.Parse(x.CodeKbn) == item.SyaSenInfoPtnKbn1).FirstOrDefault()?.CodeKbnNm,
                        SyaSenInfoPtnKbn2CodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "SENMJPTNKBN" && int.Parse(x.CodeKbn) == item.SyaSenInfoPtnKbn2).FirstOrDefault()?.CodeKbnNm,
                        SyaSenInfoPtnKbn3CodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "SENMJPTNKBN" && int.Parse(x.CodeKbn) == item.SyaSenInfoPtnKbn3).FirstOrDefault()?.CodeKbnNm,
                        SyaSenInfoPtnKbn4CodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "SENMJPTNKBN" && int.Parse(x.CodeKbn) == item.SyaSenInfoPtnKbn4).FirstOrDefault()?.CodeKbnNm,
                        SyaSenInfoPtnKbn5CodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "SENMJPTNKBN" && int.Parse(x.CodeKbn) == item.SyaSenInfoPtnKbn5).FirstOrDefault()?.CodeKbnNm,
                        SyaSenInfoPtnKbn6CodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "SENMJPTNKBN" && int.Parse(x.CodeKbn) == item.SyaSenInfoPtnKbn6).FirstOrDefault()?.CodeKbnNm,
                        SyaSenInfoPtnKbn7CodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "SENMJPTNKBN" && int.Parse(x.CodeKbn) == item.SyaSenInfoPtnKbn7).FirstOrDefault()?.CodeKbnNm,
                        SyaSenInfoPtnKbn8CodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "SENMJPTNKBN" && int.Parse(x.CodeKbn) == item.SyaSenInfoPtnKbn8).FirstOrDefault()?.CodeKbnNm,
                        SyaSenInfoPtnKbn9CodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "SENMJPTNKBN" && int.Parse(x.CodeKbn) == item.SyaSenInfoPtnKbn9).FirstOrDefault()?.CodeKbnNm,
                        SyaSenInfoPtnKbn10CodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "SENMJPTNKBN" && int.Parse(x.CodeKbn) == item.SyaSenInfoPtnKbn10).FirstOrDefault()?.CodeKbnNm,
                        SyaSenInfoPtnKbn11CodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "SENMJPTNKBN" && int.Parse(x.CodeKbn) == item.SyaSenInfoPtnKbn11).FirstOrDefault()?.CodeKbnNm,
                        SyaSenInfoPtnKbn12CodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "SENMJPTNKBN" && int.Parse(x.CodeKbn) == item.SyaSenInfoPtnKbn12).FirstOrDefault()?.CodeKbnNm,
                        SyaSenInfoPtnKbn13CodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "SENMJPTNKBN" && int.Parse(x.CodeKbn) == item.SyaSenInfoPtnKbn13).FirstOrDefault()?.CodeKbnNm,
                        SyaSenInfoPtnKbn14CodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "SENMJPTNKBN" && int.Parse(x.CodeKbn) == item.SyaSenInfoPtnKbn13).FirstOrDefault()?.CodeKbnNm,
                        SyaSenInfoPtnKbn15CodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "SENMJPTNKBN" && int.Parse(x.CodeKbn) == item.SyaSenInfoPtnKbn15).FirstOrDefault()?.CodeKbnNm,

                        JyoSenInfoPtnKbn1CodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "SENMJPTNKBN" && int.Parse(x.CodeKbn) == item.JyoSenInfoPtnKbn1).FirstOrDefault()?.CodeKbnNm,
                        JyoSenInfoPtnKbn2CodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "SENMJPTNKBN" && int.Parse(x.CodeKbn) == item.JyoSenInfoPtnKbn2).FirstOrDefault()?.CodeKbnNm,
                        JyoSenInfoPtnKbn3CodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "SENMJPTNKBN" && int.Parse(x.CodeKbn) == item.JyoSenInfoPtnKbn3).FirstOrDefault()?.CodeKbnNm,
                        JyoSenInfoPtnKbn4CodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "SENMJPTNKBN" && int.Parse(x.CodeKbn) == item.JyoSenInfoPtnKbn4).FirstOrDefault()?.CodeKbnNm,
                        JyoSenInfoPtnKbn5CodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "SENMJPTNKBN" && int.Parse(x.CodeKbn) == item.JyoSenInfoPtnKbn5).FirstOrDefault()?.CodeKbnNm,
                        JyoSenInfoPtnKbn6CodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "SENMJPTNKBN" && int.Parse(x.CodeKbn) == item.JyoSenInfoPtnKbn6).FirstOrDefault()?.CodeKbnNm,
                        JyoSenInfoPtnKbn7CodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "SENMJPTNKBN" && int.Parse(x.CodeKbn) == item.JyoSenInfoPtnKbn7).FirstOrDefault()?.CodeKbnNm,
                        JyoSenInfoPtnKbn8CodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "SENMJPTNKBN" && int.Parse(x.CodeKbn) == item.JyoSenInfoPtnKbn8).FirstOrDefault()?.CodeKbnNm,
                        JyoSenInfoPtnKbn9CodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "SENMJPTNKBN" && int.Parse(x.CodeKbn) == item.JyoSenInfoPtnKbn9).FirstOrDefault()?.CodeKbnNm,
                        JyoSenInfoPtnKbn10CodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "SENMJPTNKBN" && int.Parse(x.CodeKbn) == item.JyoSenInfoPtnKbn10).FirstOrDefault()?.CodeKbnNm,
                        JyoSenInfoPtnKbn11CodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "SENMJPTNKBN" && int.Parse(x.CodeKbn) == item.JyoSenInfoPtnKbn11).FirstOrDefault()?.CodeKbnNm,
                        JyoSenInfoPtnKbn12CodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "SENMJPTNKBN" && int.Parse(x.CodeKbn) == item.JyoSenInfoPtnKbn12).FirstOrDefault()?.CodeKbnNm,
                        JyoSenInfoPtnKbn13CodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "SENMJPTNKBN" && int.Parse(x.CodeKbn) == item.JyoSenInfoPtnKbn13).FirstOrDefault()?.CodeKbnNm,
                        JyoSenInfoPtnKbn14CodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "SENMJPTNKBN" && int.Parse(x.CodeKbn) == item.JyoSenInfoPtnKbn14).FirstOrDefault()?.CodeKbnNm,
                        JyoSenInfoPtnKbn15CodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "SENMJPTNKBN" && int.Parse(x.CodeKbn) == item.JyoSenInfoPtnKbn15).FirstOrDefault()?.CodeKbnNm,

                        SeiMukiCodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "SEIMUKI" && int.Parse(x.CodeKbn) == item.SeiMuki).FirstOrDefault()?.CodeKbnNm,
                        ETCKinKbnCodeKbnNm = codeKbnSetting.Where(x => x.CodeSyu == "ETCKINKBN" && int.Parse(x.CodeKbn) == item.EtckinKbn).FirstOrDefault()?.CodeKbnNm,


                    });
                }

                //await _context.LoadStoredProc("PK_RegulationSetting_R")
                //    .AddParam("@CompanyFrom", request.model.CompanyFrom?.CompanyCd ?? 0)
                //    .AddParam("@CompanyTo", request.model.CompanyTo?.CompanyCd ?? 0)
                //    .AddParam("@TenantCdSeq", new ClaimModel().TenantID)
                //    .ExecAsync(async es => result = await es.ToListAsync<SPModel>(), cancellationToken);


                return result;
            }
        }
    }
}
