using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HassyaAllrightCloud.Domain.Dto
{
    public class KashikiriSettingData
    {
        public int CompanyCdSeq { get; set; }
        public byte UriKbn { get; set; }
        public byte SyohiHasu { get; set; }
        public byte TesuHasu { get; set; }
        public byte HoukoKbn { get; set; }
        public byte HouZeiKbn { get; set; }
        public byte HouOutKbn { get; set; }
        public byte JkariKbn { get; set; }
        public byte AutKarJyun { get; set; }
        public byte JkbunPat { get; set; }
        public byte SyaIrePat { get; set; }
        public byte JymAchkKbn { get; set; }
        public byte UriHenKbn { get; set; }
        public byte UriMdkbn { get; set; }
        public byte UriHenKikan { get; set; }
        public byte UriZeroChk { get; set; }
        public byte CanKbn { get; set; }
        public byte CanMdkbn { get; set; }
        public byte CanKikan { get; set; }
        public byte CanWaitKbn { get; set; }
        public byte CanJidoKbn { get; set; }
        public byte YouTesuKbn { get; set; }
        public byte YouSagaKbn { get; set; }
        public byte SyaUntKbn { get; set; }
        public byte ZasyuKbn { get; set; }
        public byte FutSf1flg { get; set; }
        public byte FutSf2flg { get; set; }
        public byte FutSf3flg { get; set; }
        public byte FutSf4flg { get; set; }
        public byte SokoJunKbn { get; set; }
        public byte UntZeiKbn { get; set; }
        public byte TumZeiKbn { get; set; }
        public string ColKari { get; set; }
        public string ColKariH { get; set; }
        public string ColNin { get; set; }
        public string ColHai { get; set; }
        public string ColHaiin { get; set; }
        public string ColWari { get; set; }
        public string ColShiha { get; set; }
        public string ColKaku { get; set; }
        public string ColNip { get; set; }
        public string ColNyu { get; set; }
        public string ColYou { get; set; }
        public string ColMiKari { get; set; }
        public string ColIcKari { get; set; }
        public string ColIcKariH { get; set; }
        public string ColIcHai { get; set; }
        public string ColIcHaiin { get; set; }
        public string ColIcWari { get; set; }
        public string ColIcShiha { get; set; }
        public string ColIcNip { get; set; }
        public string ColIcNyu { get; set; }
        public string ColIcYou { get; set; }
        public string ColNcou { get; set; }
        public string ColIcNcou { get; set; }
        public string ColScou { get; set; }
        public string ColIcScou { get; set; }
        public string ColKyoy { get; set; }
        public string ColSelect { get; set; }
        public string ColKanyu { get; set; }
        public string ColKahar { get; set; }
        public byte SryHyjSyu { get; set; }
        public byte SryHyjHga { get; set; }
        public byte SryHyjTde { get; set; }
        public byte SryHyjTch { get; set; }
        public byte SryHyjTka { get; set; }
        public decimal CanRit1 { get; set; }
        public byte CanSkan1 { get; set; }
        public byte CanEkan1 { get; set; }
        public decimal CanRit2 { get; set; }
        public byte CanSkan2 { get; set; }
        public byte CanEkan2 { get; set; }
        public decimal CanRit3 { get; set; }
        public byte CanSkan3 { get; set; }
        public byte CanEkan3 { get; set; }
        public decimal CanRit4 { get; set; }
        public byte CanSkan4 { get; set; }
        public byte CanEkan4 { get; set; }
        public decimal CanRit5 { get; set; }
        public byte CanSkan5 { get; set; }
        public byte CanEkan5 { get; set; }
        public decimal CanRit6 { get; set; }
        public byte CanSkan6 { get; set; }
        public byte CanEkan6 { get; set; }
        public byte GetSyoKbn { get; set; }
        public byte SeiKrksKbn { get; set; }
        public byte DaySyoKbn { get; set; }
        public byte KouYouSet { get; set; }
        public byte AutKouKbn { get; set; }
        public byte SenHyoHi { get; set; }
        public byte SenYouDefFlg { get; set; }
        public byte SenMikDefFlg { get; set; }
        public byte KoteiCopyFlg { get; set; }
        public byte FutaiCopyFlg { get; set; }
        public byte TumiCopyFlg { get; set; }
        public byte TehaiCopyFlg { get; set; }
        public byte JoshaCopyFlg { get; set; }
        public byte YykCopyFlg { get; set; }
        public byte UkbCopyFlg { get; set; }
        public byte SeiGenFlg { get; set; }
        public byte MeiShyKbn { get; set; }
        public byte SyaSenMjPtnKbn1 { get; set; }
        public string SyaSenMjPtnCol1 { get; set; }
        public byte SyaSenMjPtnKbn2 { get; set; }
        public string SyaSenMjPtnCol2 { get; set; }
        public byte SyaSenMjPtnKbn3 { get; set; }
        public string SyaSenMjPtnCol3 { get; set; }
        public byte SyaSenMjPtnKbn4 { get; set; }
        public string SyaSenMjPtnCol4 { get; set; }
        public byte SyaSenMjPtnKbn5 { get; set; }
        public string SyaSenMjPtnCol5 { get; set; }
        public byte JyoSenMjPtnKbn1 { get; set; }
        public string JyoSenMjPtnCol1 { get; set; }
        public byte JyoSenMjPtnKbn2 { get; set; }
        public string JyoSenMjPtnCol2 { get; set; }
        public byte JyoSenMjPtnKbn3 { get; set; }
        public string JyoSenMjPtnCol3 { get; set; }
        public byte JyoSenMjPtnKbn4 { get; set; }
        public string JyoSenMjPtnCol4 { get; set; }
        public byte JyoSenMjPtnKbn5 { get; set; }
        public string JyoSenMjPtnCol5 { get; set; }
        public string SeiCom1 { get; set; }
        public string SeiCom2 { get; set; }
        public string SeiCom3 { get; set; }
        public string SeiCom4 { get; set; }
        public string SeiCom5 { get; set; }
        public string SeiCom6 { get; set; }
        public string JisKinKyuNm01 { get; set; }
        public string JisKinKyuNm02 { get; set; }
        public string JisKinKyuNm03 { get; set; }
        public string JisKinKyuNm04 { get; set; }
        public string JisKinKyuNm05 { get; set; }
        public string JisKinKyuNm06 { get; set; }
        public string JisKinKyuNm07 { get; set; }
        public string JisKinKyuNm08 { get; set; }
        public string JisKinKyuNm09 { get; set; }
        public string JisKinKyuNm10 { get; set; }
        public byte SyaSenInfoPtnKbn1 { get; set; }
        public string SyaSenInfoPtnCol1 { get; set; }
        public byte SyaSenInfoPtnKbn2 { get; set; }
        public string SyaSenInfoPtnCol2 { get; set; }
        public byte SyaSenInfoPtnKbn3 { get; set; }
        public string SyaSenInfoPtnCol3 { get; set; }
        public byte SyaSenInfoPtnKbn4 { get; set; }
        public string SyaSenInfoPtnCol4 { get; set; }
        public byte SyaSenInfoPtnKbn5 { get; set; }
        public string SyaSenInfoPtnCol5 { get; set; }
        public byte SyaSenInfoPtnKbn6 { get; set; }
        public string SyaSenInfoPtnCol6 { get; set; }
        public byte SyaSenInfoPtnKbn7 { get; set; }
        public string SyaSenInfoPtnCol7 { get; set; }
        public byte SyaSenInfoPtnKbn8 { get; set; }
        public string SyaSenInfoPtnCol8 { get; set; }
        public byte SyaSenInfoPtnKbn9 { get; set; }
        public string SyaSenInfoPtnCol9 { get; set; }
        public byte SyaSenInfoPtnKbn10 { get; set; }
        public string SyaSenInfoPtnCol10 { get; set; }
        public byte SyaSenInfoPtnKbn11 { get; set; }
        public string SyaSenInfoPtnCol11 { get; set; }
        public byte SyaSenInfoPtnKbn12 { get; set; }
        public string SyaSenInfoPtnCol12 { get; set; }
        public byte SyaSenInfoPtnKbn13 { get; set; }
        public string SyaSenInfoPtnCol13 { get; set; }
        public byte SyaSenInfoPtnKbn14 { get; set; }
        public string SyaSenInfoPtnCol14 { get; set; }
        public byte SyaSenInfoPtnKbn15 { get; set; }
        public string SyaSenInfoPtnCol15 { get; set; }
        public byte JyoSenInfoPtnKbn1 { get; set; }
        public string JyoSenInfoPtnCol1 { get; set; }
        public byte JyoSenInfoPtnKbn2 { get; set; }
        public string JyoSenInfoPtnCol2 { get; set; }
        public byte JyoSenInfoPtnKbn3 { get; set; }
        public string JyoSenInfoPtnCol3 { get; set; }
        public byte JyoSenInfoPtnKbn4 { get; set; }
        public string JyoSenInfoPtnCol4 { get; set; }
        public byte JyoSenInfoPtnKbn5 { get; set; }
        public string JyoSenInfoPtnCol5 { get; set; }
        public byte JyoSenInfoPtnKbn6 { get; set; }
        public string JyoSenInfoPtnCol6 { get; set; }
        public byte JyoSenInfoPtnKbn7 { get; set; }
        public string JyoSenInfoPtnCol7 { get; set; }
        public byte JyoSenInfoPtnKbn8 { get; set; }
        public string JyoSenInfoPtnCol8 { get; set; }
        public byte JyoSenInfoPtnKbn9 { get; set; }
        public string JyoSenInfoPtnCol9 { get; set; }
        public byte JyoSenInfoPtnKbn10 { get; set; }
        public string JyoSenInfoPtnCol10 { get; set; }
        public byte JyoSenInfoPtnKbn11 { get; set; }
        public string JyoSenInfoPtnCol11 { get; set; }
        public byte JyoSenInfoPtnKbn12 { get; set; }
        public string JyoSenInfoPtnCol12 { get; set; }
        public byte JyoSenInfoPtnKbn13 { get; set; }
        public string JyoSenInfoPtnCol13 { get; set; }
        public byte JyoSenInfoPtnKbn14 { get; set; }
        public string JyoSenInfoPtnCol14 { get; set; }
        public byte JyoSenInfoPtnKbn15 { get; set; }
        public string JyoSenInfoPtnCol15 { get; set; }
        public byte JyoSyaChkSiyoKbn { get; set; }
        public byte SenDayRenge { get; set; }
        public short SenDefWidth { get; set; }
        public string YykHaiStime { get; set; }
        public string YykTouTime { get; set; }
        public byte TehaiAutoSet { get; set; }
        public byte GoSyaAutoSet { get; set; }
        public byte YoySyuKiTimeSiyoKbn { get; set; }
        public byte KarSyuKiTimeSiyoKbn { get; set; }
        public byte GuiAutoSet { get; set; }
        public byte DrvAutoSet { get; set; }
        public byte SenBackPtnKbn { get; set; }
        public string SenBackPtnCol { get; set; }
        public byte SenObptnKbn { get; set; }
        public string SenObptnCol { get; set; }
        public int FutTumCdSeq { get; set; }
        public byte EtckinKbn { get; set; }
        public int SeisanCdSeq { get; set; }
        public int GuideFutTumCdSeq { get; set; }
        public byte SeiMuki { get; set; }
        public string ExpItem { get; set; }
        public string UpdYmd { get; set; }
        public string UpdTime { get; set; }
        public int UpdSyainCd { get; set; }
        public string UpdPrgId { get; set; }
        public byte QuotationTransfer { get; set; }
        public string KaizenKijunYmd { get; set; }
        public int CompanyCdSeqCompanyCd { get; set; }
        public string CompanyCdSeqCompanyNm { get; set; }
        public string CompanyCdSeqRyakuNm { get; set; }
        public string SyainCd { get; set; }
        public string SyainNm { get; set; }
    }
}
