using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HassyaAllrightCloud.Domain.Dto
{
    public class KobanDataGridModel
    {
        public int SyainCdSeq { get; set; }
        public string SyainCd { get; set; }
        public string SyainNm { get; set; }
        public int CompanyCd { get; set; }
        public int SyainEigyoCd { get; set; }
        public string SyainEigyoNm { get; set; }
        public string SyainTenkoNo { get; set; }
        public int SyaRyoCd { get; set; }
        public short SyaSyuCd { get; set; }
        public int SyaRyoEigyoCd { get; set; }
        public string SyaRyoEigyoNm { get; set; }
        public string SyaRyoTenkoNo { get; set; }
        public string SyokumuNm { get; set; }
        public short SyokumuCd { get; set; }
        public string GyomuKbn { get; set; }
        public string SyaSyuSort { get; set; }
        public short Day01KinKyuCd { get; set; }
        public string Day01KinKyuNm { get; set; }
        public int Day01SelectKbn { get; set; }
        public short Day02KinKyuCd { get; set; }
        public string Day02KinKyuNm { get; set; }
        public int Day02SelectKbn { get; set; }
        public short Day03KinKyuCd { get; set; }
        public string Day03KinKyuNm { get; set; }
        public int Day03SelectKbn { get; set; }
        public short Day04KinKyuCd { get; set; }
        public string Day04KinKyuNm { get; set; }
        public int Day04SelectKbn { get; set; }
        public short Day05KinKyuCd { get; set; }
        public string Day05KinKyuNm { get; set; }
        public int Day05SelectKbn { get; set; }
        public short Day06KinKyuCd { get; set; }
        public string Day06KinKyuNm { get; set; }
        public int Day06SelectKbn { get; set; }
        public short Day07KinKyuCd { get; set; }
        public string Day07KinKyuNm { get; set; }
        public int Day07SelectKbn { get; set; }
        public short Day08KinKyuCd { get; set; }
        public string Day08KinKyuNm { get; set; }
        public int Day08SelectKbn { get; set; }
        public short Day09KinKyuCd { get; set; }
        public string Day09KinKyuNm { get; set; }
        public int Day09SelectKbn { get; set; }
        public short Day10KinKyuCd { get; set; }
        public string Day10KinKyuNm { get; set; }
        public int Day10SelectKbn { get; set; }
        public short Day11KinKyuCd { get; set; }
        public string Day11KinKyuNm { get; set; }
        public int Day11SelectKbn { get; set; }
        public short Day12KinKyuCd { get; set; }
        public string Day12KinKyuNm { get; set; }
        public int Day12SelectKbn { get; set; }
        public short Day13KinKyuCd { get; set; }
        public string Day13KinKyuNm { get; set; }
        public int Day13SelectKbn { get; set; }
        public short Day14KinKyuCd { get; set; }
        public string Day14KinKyuNm { get; set; }
        public int Day14SelectKbn { get; set; }
        public short Day15KinKyuCd { get; set; }
        public string Day15KinKyuNm { get; set; }
        public int Day15SelectKbn { get; set; }
        public short Day16KinKyuCd { get; set; }
        public string Day16KinKyuNm { get; set; }
        public int Day16SelectKbn { get; set; }
        public short Day17KinKyuCd { get; set; }
        public string Day17KinKyuNm { get; set; }
        public int Day17SelectKbn { get; set; }
        public short Day18KinKyuCd { get; set; }
        public string Day18KinKyuNm { get; set; }
        public int Day18SelectKbn { get; set; }
        public short Day19KinKyuCd { get; set; }
        public string Day19KinKyuNm { get; set; }
        public int Day19SelectKbn { get; set; }
        public short Day20KinKyuCd { get; set; }
        public string Day20KinKyuNm { get; set; }
        public int Day20SelectKbn { get; set; }
        public short Day21KinKyuCd { get; set; }
        public string Day21KinKyuNm { get; set; }
        public int Day21SelectKbn { get; set; }
        public short Day22KinKyuCd { get; set; }
        public string Day22KinKyuNm { get; set; }
        public int Day22SelectKbn { get; set; }
        public short Day23KinKyuCd { get; set; }
        public string Day23KinKyuNm { get; set; }
        public int Day23SelectKbn { get; set; }
        public short Day24KinKyuCd { get; set; }
        public string Day24KinKyuNm { get; set; }
        public int Day24SelectKbn { get; set; }
        public short Day25KinKyuCd { get; set; }
        public string Day25KinKyuNm { get; set; }
        public int Day25SelectKbn { get; set; }
        public short Day26KinKyuCd { get; set; }
        public string Day26KinKyuNm { get; set; }
        public int Day26SelectKbn { get; set; }
        public short Day27KinKyuCd { get; set; }
        public string Day27KinKyuNm { get; set; }
        public int Day27SelectKbn { get; set; }
        public short Day28KinKyuCd { get; set; }
        public string Day28KinKyuNm { get; set; }
        public int Day28SelectKbn { get; set; }
        public short Day29KinKyuCd { get; set; }
        public string Day29KinKyuNm { get; set; }
        public int Day29SelectKbn { get; set; }
        public short Day30KinKyuCd { get; set; }
        public string Day30KinKyuNm { get; set; }
        public int Day30SelectKbn { get; set; }
        public short Day31KinKyuCd { get; set; }
        public string Day31KinKyuNm { get; set; }
        public int Day31SelectKbn { get; set; }
        public int Day01CalenKbn { get; set; }
        public int Day02CalenKbn { get; set; }
        public int Day03CalenKbn { get; set; }
        public int Day04CalenKbn { get; set; }
        public int Day05CalenKbn { get; set; }
        public int Day06CalenKbn { get; set; }
        public int Day07CalenKbn { get; set; }
        public int Day08CalenKbn { get; set; }
        public int Day09CalenKbn { get; set; }
        public int Day10CalenKbn { get; set; }
        public int Day11CalenKbn { get; set; }
        public int Day12CalenKbn { get; set; }
        public int Day13CalenKbn { get; set; }
        public int Day14CalenKbn { get; set; }
        public int Day15CalenKbn { get; set; }
        public int Day16CalenKbn { get; set; }
        public int Day17CalenKbn { get; set; }
        public int Day18CalenKbn { get; set; }
        public int Day19CalenKbn { get; set; }
        public int Day20CalenKbn { get; set; }
        public int Day21CalenKbn { get; set; }
        public int Day22CalenKbn { get; set; }
        public int Day23CalenKbn { get; set; }
        public int Day24CalenKbn { get; set; }
        public int Day25CalenKbn { get; set; }
        public int Day26CalenKbn { get; set; }
        public int Day27CalenKbn { get; set; }
        public int Day28CalenKbn { get; set; }
        public int Day29CalenKbn { get; set; }
        public int Day30CalenKbn { get; set; }
        public int Day31CalenKbn { get; set; }

    }
}
