using System.Collections.Generic;

namespace HassyaAllrightCloud.Domain.Dto
{
    public class LineInfoListData
    {
        public static List<LineInfo> lineInfoItem = new List<LineInfo>
        {
            new LineInfo { Id = 0, text = "", fieldname = ""},
            new LineInfo { Id = 1, text = "号車", fieldname = "Haisha_GoSya"},
            new LineInfo { Id = 2, text = "車種名", fieldname = "SyaSyu_SyaSyuNm"},
            new LineInfo { Id = 3, text = "車種記号 ", fieldname = "SyaSyu_SyaSyuKigo"},
            new LineInfo { Id = 4, text = "車号 ", fieldname = "SyaRyo_SyaRyoNm"},
            new LineInfo { Id = 5, text = "出庫営業所名  ", fieldname = "Eigyoshos_RyakuNm"},
            new LineInfo { Id = 6, text = "帰庫営業所名", fieldname = "Eigyoshos1_RyakuNm"},
            new LineInfo { Id = 7, text = "団体名 ", fieldname = "Unkobi_DanTaNm"},
            new LineInfo { Id = 8, text = "行き先名 ", fieldname = "Haisha_IkNm"},
            new LineInfo { Id = 9, text = "得意先名  ", fieldname = "TokiSk_RyakuNm"},
            new LineInfo { Id = 10, text = "出庫年月日 ", fieldname = "Haisha_SyuKoYmd"},
            new LineInfo { Id = 11, text = "出庫時間 ", fieldname = "Haisha_SyuKoTime"},
            new LineInfo { Id = 12, text = "出発時間   ", fieldname = "Haisha_SyuPaTime"},
            new LineInfo { Id = 13, text = "配車年月日   ", fieldname = "Haisha_HaiSYmd"},
            new LineInfo { Id = 14, text = "配車時間  ", fieldname = "Haisha_HaiSTime"},
            new LineInfo { Id = 15, text = "配車地名", fieldname = "Haisha_HaiSNm"},
            new LineInfo { Id = 16, text = "配車地交通機関名", fieldname = "Haisha_HaiSKouKNm"},
            new LineInfo { Id = 17, text = "配車地便名", fieldname = "Haisha_HaisBinNm"},
            new LineInfo { Id = 18, text = "配車地接続時間  ", fieldname = "Haisha_HaiSSetTime"},
            new LineInfo { Id = 19, text = "配車地記号", fieldname = "Haisha_HaiSKigou"},
            new LineInfo { Id = 20, text = "帰庫年月日  ", fieldname = "Haisha_KikYmd"},
            new LineInfo { Id = 21, text = "帰庫時間", fieldname = "Haisha_KikTime"},
            new LineInfo { Id = 22, text = "到着年月日", fieldname = "Haisha_TouYmd"},
            new LineInfo { Id = 23, text = "到着時間", fieldname = "Haisha_TouChTime"},
            new LineInfo { Id = 24, text = "到着地名", fieldname = "Haisha_TouNm"},
            new LineInfo { Id = 25, text = "到着地交通機関名", fieldname = "Haisha_TouSKouKNm"},
            new LineInfo { Id = 26, text = "到着地便名", fieldname = "Haisha_TouSBinNm"},
            new LineInfo { Id = 27, text = "到着地接続時間  ", fieldname = "Haisha_TouSetTime"},
            new LineInfo { Id = 28, text = "到着地記号", fieldname = "Haisha_TouKigou"},
            new LineInfo { Id = 29, text = "乗車人員", fieldname = "Haisha_JyoSyaJin"},
            new LineInfo { Id = 30, text = "プラス人員  ", fieldname = "Haisha_PlusJin"},
            new LineInfo { Id = 31, text = "運転手数  ", fieldname = "Haisha_DrvJin"},
            new LineInfo { Id = 32, text = "ガイド数  ", fieldname = "Haisha_GuiSu"},
            new LineInfo { Id = 33, text = "その他人員１数  ", fieldname = "Haisha_OthJin1"},
            new LineInfo { Id = 34, text = "その他人員２数 ", fieldname = "Haisha_OthJin2"},
            new LineInfo { Id = 35, text = "プレート№", fieldname = "Haisha_PlatNo"},
            new LineInfo { Id = 36, text = "配車コメント", fieldname = "Haisha_HaiCom"},
            new LineInfo { Id = 37, text = "金額", fieldname = "Haisha_SyaRyoUnc"},
            new LineInfo { Id = 38, text = "受付条件", fieldname = "UKEJOKEN_CodeKbnNm"},
            new LineInfo { Id = 39, text = "配車住所①", fieldname = "Haisha_HaiSJyus1"},
            new LineInfo { Id = 40, text = "配車住所②", fieldname = "Haisha_HaiSJyus2"},
            new LineInfo { Id = 41, text = "到着住所①", fieldname = "Haisha_TouJyusyo1"},
            new LineInfo { Id = 42, text = "到着住所②", fieldname = "Haisha_TouJyusyo2"},
            new LineInfo { Id =43, text = "", fieldname = ""},
            new LineInfo { Id =44, text = "備考(予約)", fieldname = "Yyksho_BikoNm"},
            new LineInfo { Id =45, text = "備考(運行)", fieldname = "Unkobi_BikoNm"},
            new LineInfo { Id =46, text = "備考(配車)", fieldname = "Haisha_BikoNm"},
            new LineInfo { Id = 47, text = "指示書番号", fieldname = ""},
            new LineInfo { Id =48, text = "車輌定員", fieldname = "SyaRyo_TeiCnt"},
            new LineInfo { Id =49, text = "指示区分①", fieldname = "SIJJOKBN1_CodeKbnNm"},
            new LineInfo { Id =50, text = "指示区分②", fieldname = "SIJJOKBN2_CodeKbnNm"},
            new LineInfo { Id =51, text = "指示区分③", fieldname = "SIJJOKBN3_CodeKbnNm"},
            new LineInfo { Id =52, text = "指示区分④", fieldname = "SIJJOKBN4_CodeKbnNm"},
            new LineInfo { Id =53, text = "指示区分⑤", fieldname = "SIJJOKBN5_CodeKbnNm"},
            new LineInfo { Id =54, text = "予約車種", fieldname = "YySyasyu_SyaSyuNm"},
            new LineInfo { Id =55, text = "", fieldname = ""},
            new LineInfo { Id =56, text = "", fieldname = ""},
            new LineInfo { Id = 57, text = "配車時間（配車地名）", fieldname = ""},
            new LineInfo { Id =58, text = "到着時間（到着地名）", fieldname = ""},
            new LineInfo { Id =59, text = "", fieldname = ""},
            new LineInfo { Id =60, text = "金額(税抜)", fieldname = "Haisha_SyaRyoUnc"},
            new LineInfo { Id =61, text = "営業担当者", fieldname = "Eigyotan_SyainNm"},
            new LineInfo { Id =62, text = "入力担当者", fieldname = "Syain_SyainNm"},
            new LineInfo { Id =63, text = "", fieldname = ""},            
        };
    }
}
