//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HassyaAllrightCloud.Reports.ReportTemplate.UnkoushijishoReport {
    
    public partial class UnkoushijishoSubReport : DevExpress.XtraReports.UI.XtraReport {
        private void InitializeComponent() {
            DevExpress.XtraReports.ReportInitializer reportInitializer = new DevExpress.XtraReports.ReportInitializer(this, "HassyaAllrightCloud.Reports.ReportTemplate.UnkoushijishoReport.UnkoushijishoSubRe" +
                    "port.repx");

            // Controls
            this.topMarginBand1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.TopMarginBand>("topMarginBand1");
            this.detailBand1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("detailBand1");
            this.bottomMarginBand1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.BottomMarginBand>("bottomMarginBand1");
            this.GroupHeader1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.GroupHeaderBand>("GroupHeader1");
            this.subreport2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRSubreport>("subreport2");
            this.subreport2.ReportSource = new HassyaAllrightCloud.Reports.ReportTemplate.UnkoushijishoReport.TehaiSubReport();
            this.subreport1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRSubreport>("subreport1");
            this.subreport1.ReportSource = new HassyaAllrightCloud.Reports.ReportTemplate.UnkoushijishoReport.KoteiSubReport();

            // Parameters
            this.Ukeno = reportInitializer.GetParameter("Ukeno");
            this.SyuKoYmd = reportInitializer.GetParameter("SyuKoYmd");
            this.TeiDanNo = reportInitializer.GetParameter("TeiDanNo");
            this.BunkRen = reportInitializer.GetParameter("BunkRen");
            this.UnkRen = reportInitializer.GetParameter("UnkRen");
            this.KikYmd = reportInitializer.GetParameter("KikYmd");

            // Data Sources
            this.sqlDataSource1 = reportInitializer.GetDataSource<DevExpress.DataAccess.Sql.SqlDataSource>("sqlDataSource1");
        }
        private DevExpress.XtraReports.UI.TopMarginBand topMarginBand1;
        private DevExpress.XtraReports.UI.DetailBand detailBand1;
        private DevExpress.XtraReports.UI.BottomMarginBand bottomMarginBand1;
        private DevExpress.XtraReports.UI.GroupHeaderBand GroupHeader1;
        private DevExpress.XtraReports.UI.XRSubreport subreport2;
        private DevExpress.XtraReports.UI.XRSubreport subreport1;
        private DevExpress.DataAccess.Sql.SqlDataSource sqlDataSource1;
        private DevExpress.XtraReports.Parameters.Parameter Ukeno;
        private DevExpress.XtraReports.Parameters.Parameter SyuKoYmd;
        private DevExpress.XtraReports.Parameters.Parameter TeiDanNo;
        private DevExpress.XtraReports.Parameters.Parameter BunkRen;
        private DevExpress.XtraReports.Parameters.Parameter UnkRen;
        private DevExpress.XtraReports.Parameters.Parameter KikYmd;
    }
}
