// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using HassyaAllrightCloud.Domain.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace HassyaAllrightCloud.Infrastructure.Persistence
{
    public class LkdShabniConfiguration : IEntityTypeConfiguration<LkdShabni>
    {
        public void Configure(EntityTypeBuilder<LkdShabni> entity)
        {
            entity.HasKey(e => e.LogSeq)
                .HasName("LKD_Shabni1");

            entity.ToTable("LKD_Shabni");

            entity.Property(e => e.EndMeter).HasColumnType("numeric(9, 2)");

            entity.Property(e => e.HenKeyItm)
                .IsRequired()
                .HasMaxLength(4000);

            entity.Property(e => e.JisaIpkm)
                .HasColumnName("JisaIPKm")
                .HasColumnType("numeric(7, 2)");

            entity.Property(e => e.JisaKskm)
                .HasColumnName("JisaKSKm")
                .HasColumnType("numeric(7, 2)");

            entity.Property(e => e.KisoIpkm)
                .HasColumnName("KisoIPkm")
                .HasColumnType("numeric(7, 2)");

            entity.Property(e => e.KisoKokm)
                .HasColumnName("KisoKOKm")
                .HasColumnType("numeric(7, 2)");

            entity.Property(e => e.Nenryo1).HasColumnType("numeric(5, 2)");

            entity.Property(e => e.Nenryo2).HasColumnType("numeric(5, 2)");

            entity.Property(e => e.Nenryo3).HasColumnType("numeric(5, 2)");

            entity.Property(e => e.OthKm).HasColumnType("numeric(7, 2)");

            entity.Property(e => e.StMeter).HasColumnType("numeric(9, 2)");

            entity.Property(e => e.UkeNo)
                .IsRequired()
                .HasMaxLength(15)
                .IsFixedLength();

            entity.Property(e => e.UnkYmd)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UpdPrgId)
                .IsRequired()
                .HasColumnName("UpdPrgID")
                .HasMaxLength(10)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UpdTime)
                .IsRequired()
                .HasMaxLength(6)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UpdYmd)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.Zeiritsu).HasColumnType("numeric(3, 1)");
        }
    }
}
