// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using HassyaAllrightCloud.Domain.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace HassyaAllrightCloud.Infrastructure.Persistence
{
    public class LkdTehaiConfiguration : IEntityTypeConfiguration<LkdTehai>
    {
        public void Configure(EntityTypeBuilder<LkdTehai> entity)
        {
            entity.HasKey(e => e.LogSeq)
                .HasName("LKD_Tehai1");

            entity.ToTable("LKD_Tehai");

            entity.Property(e => e.BikoNm)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.HenKeyItm)
                .IsRequired()
                .HasMaxLength(4000);

            entity.Property(e => e.SyuPaTime)
                .IsRequired()
                .HasMaxLength(4)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.TehFax)
                .IsRequired()
                .HasMaxLength(14)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.TehJyus1)
                .IsRequired()
                .HasMaxLength(30);

            entity.Property(e => e.TehJyus2)
                .IsRequired()
                .HasMaxLength(30);

            entity.Property(e => e.TehNm)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.TehTan)
                .IsRequired()
                .HasMaxLength(20);

            entity.Property(e => e.TehTel)
                .IsRequired()
                .HasMaxLength(14)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.TouChTime)
                .IsRequired()
                .HasMaxLength(4)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UkeNo)
                .IsRequired()
                .HasMaxLength(15)
                .IsFixedLength();

            entity.Property(e => e.UpdPrgId)
                .IsRequired()
                .HasColumnName("UpdPrgID")
                .HasMaxLength(10)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UpdTime)
                .IsRequired()
                .HasMaxLength(6)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UpdYmd)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();
        }
    }
}
