// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using HassyaAllrightCloud.Domain.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace HassyaAllrightCloud.Infrastructure.Persistence
{
    public class LkdUnkobiConfiguration : IEntityTypeConfiguration<LkdUnkobi>
    {
        public void Configure(EntityTypeBuilder<LkdUnkobi> entity)
        {
            entity.HasKey(e => e.LogSeq)
                .HasName("LKD_Unkobi1");

            entity.ToTable("LKD_Unkobi");

            entity.Property(e => e.AreaNm)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.DanTaKana)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.DanTaNm)
                .IsRequired()
                .HasMaxLength(100);

            entity.Property(e => e.GuiWnin).HasColumnName("GuiWNin");

            entity.Property(e => e.HaiIkbn).HasColumnName("HaiIKbn");

            entity.Property(e => e.HaiSbinCdSeq).HasColumnName("HaiSBinCdSeq");

            entity.Property(e => e.HaiScdSeq).HasColumnName("HaiSCdSeq");

            entity.Property(e => e.HaiSjyus1)
                .IsRequired()
                .HasColumnName("HaiSJyus1")
                .HasMaxLength(30);

            entity.Property(e => e.HaiSjyus2)
                .IsRequired()
                .HasColumnName("HaiSJyus2")
                .HasMaxLength(30);

            entity.Property(e => e.HaiSkbn).HasColumnName("HaiSKbn");

            entity.Property(e => e.HaiSkouKcdSeq).HasColumnName("HaiSKouKCdSeq");

            entity.Property(e => e.HaiSnm)
                .IsRequired()
                .HasColumnName("HaiSNm")
                .HasMaxLength(50);

            entity.Property(e => e.HaiSsetTime)
                .IsRequired()
                .HasColumnName("HaiSSetTime")
                .HasMaxLength(4)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.HaiStime)
                .IsRequired()
                .HasColumnName("HaiSTime")
                .HasMaxLength(4)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.HaiSymd)
                .IsRequired()
                .HasColumnName("HaiSYmd")
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.HasNm)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.HenKeyItm)
                .IsRequired()
                .HasMaxLength(4000);

            entity.Property(e => e.IkNm)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.KanDmhflg).HasColumnName("KanDMHFlg");

            entity.Property(e => e.KanJnm)
                .IsRequired()
                .HasColumnName("KanJNm")
                .HasMaxLength(20);

            entity.Property(e => e.KanjFax)
                .IsRequired()
                .HasMaxLength(14)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.KanjJyus1)
                .IsRequired()
                .HasMaxLength(30);

            entity.Property(e => e.KanjJyus2)
                .IsRequired()
                .HasMaxLength(30);

            entity.Property(e => e.KanjKeiNo)
                .IsRequired()
                .HasMaxLength(14)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.KanjMail)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.KanjTel)
                .IsRequired()
                .HasMaxLength(14)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.KhinKbn).HasColumnName("KHinKbn");

            entity.Property(e => e.KikTime)
                .IsRequired()
                .HasMaxLength(4)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.Kskbn).HasColumnName("KSKbn");

            entity.Property(e => e.SyuKoTime)
                .IsRequired()
                .HasMaxLength(4)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.SyuPaTime)
                .IsRequired()
                .HasMaxLength(4)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.TouChTime)
                .IsRequired()
                .HasMaxLength(4)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.TouJyusyo1)
                .IsRequired()
                .HasMaxLength(30);

            entity.Property(e => e.TouJyusyo2)
                .IsRequired()
                .HasMaxLength(30);

            entity.Property(e => e.TouKouKcdSeq).HasColumnName("TouKouKCdSeq");

            entity.Property(e => e.TouNm)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.TouSetTime)
                .IsRequired()
                .HasMaxLength(4)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.TouYmd)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UkeNo)
                .IsRequired()
                .HasMaxLength(15)
                .IsFixedLength();

            entity.Property(e => e.UnkoJkbn).HasColumnName("UnkoJKbn");

            entity.Property(e => e.UpdPrgId)
                .IsRequired()
                .HasColumnName("UpdPrgID")
                .HasMaxLength(10)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UpdTime)
                .IsRequired()
                .HasMaxLength(6)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UpdYmd)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UriYmd)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();
        }
    }
}
