// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using HassyaAllrightCloud.Domain.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace HassyaAllrightCloud.Infrastructure.Persistence
{
    public class LkdYykshoConfiguration : IEntityTypeConfiguration<LkdYyksho>
    {
        public void Configure(EntityTypeBuilder<LkdYyksho> entity)
        {
            entity.HasKey(e => e.LogSeq)
                .HasName("LKD_Yyksho1");

            entity.ToTable("LKD_Yyksho");

            entity.Property(e => e.CanFuRiy)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.CanFuYmd)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.CanRit).HasColumnType("numeric(4, 1)");

            entity.Property(e => e.CanRiy)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.CanSyoR).HasColumnType("numeric(3, 1)");

            entity.Property(e => e.CanYmd)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.CanZkbn).HasColumnName("CanZKbn");

            entity.Property(e => e.GuiWnin).HasColumnName("GuiWNin");

            entity.Property(e => e.HaiIkbn).HasColumnName("HaiIKbn");

            entity.Property(e => e.HaiSkbn).HasColumnName("HaiSKbn");

            entity.Property(e => e.HenKeyItm)
                .IsRequired()
                .HasMaxLength(4000);

            entity.Property(e => e.KaktYmd)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.KhinKbn).HasColumnName("KHinKbn");

            entity.Property(e => e.Kskbn).HasColumnName("KSKbn");

            entity.Property(e => e.NcouKbn).HasColumnName("NCouKbn");

            entity.Property(e => e.ScouKbn).HasColumnName("SCouKbn");

            entity.Property(e => e.SeiTaiYmd)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.SeikYm)
                .IsRequired()
                .HasMaxLength(6)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.TesuRitu).HasColumnType("numeric(3, 1)");

            entity.Property(e => e.TesuRyoG).HasColumnType("numeric(9, 0)");

            entity.Property(e => e.TokuiFax)
                .IsRequired()
                .HasMaxLength(14)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.TokuiMail)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.TokuiTanNm)
                .IsRequired()
                .HasMaxLength(16);

            entity.Property(e => e.TokuiTel)
                .IsRequired()
                .HasMaxLength(14)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.TourCd)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UkeNo)
                .IsRequired()
                .HasMaxLength(15)
                .IsFixedLength();

            entity.Property(e => e.UkeYmd)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UntKin).HasColumnType("numeric(9, 0)");

            entity.Property(e => e.UpdPrgId)
                .IsRequired()
                .HasColumnName("UpdPrgID")
                .HasMaxLength(10)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UpdTime)
                .IsRequired()
                .HasMaxLength(6)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UpdYmd)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.YoyaKana)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.YoyaNm)
                .IsRequired()
                .HasMaxLength(100);

            entity.Property(e => e.ZeiRui).HasColumnType("numeric(9, 0)");

            entity.Property(e => e.Zeiritsu).HasColumnType("numeric(3, 1)");
        }
    }
}
