// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using HassyaAllrightCloud.Domain.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace HassyaAllrightCloud.Infrastructure.Persistence
{
    public class LkdYfutTuConfiguration : IEntityTypeConfiguration<LkdYfutTu>
    {
        public void Configure(EntityTypeBuilder<LkdYfutTu> entity)
        {
            entity.HasKey(e => e.LogSeq)
                .HasName("LKD_YFutTu1");

            entity.ToTable("LKD_YFutTu");

            entity.Property(e => e.DeRyoCd)
                .IsRequired()
                .HasMaxLength(3)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.DeRyoNm)
                .IsRequired()
                .HasMaxLength(10);

            entity.Property(e => e.FutTumNm)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.HasYmd)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.HenKeyItm)
                .IsRequired()
                .HasMaxLength(4000);

            entity.Property(e => e.IriRyoCd)
                .IsRequired()
                .HasMaxLength(3)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.IriRyoNm)
                .IsRequired()
                .HasMaxLength(10);

            entity.Property(e => e.ScouKbn).HasColumnName("SCouKbn");

            entity.Property(e => e.SeisanNm)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.TesuRitu).HasColumnType("numeric(3, 1)");

            entity.Property(e => e.UkeNo)
                .IsRequired()
                .HasMaxLength(15)
                .IsFixedLength();

            entity.Property(e => e.UpdPrgId)
                .IsRequired()
                .HasColumnName("UpdPrgID")
                .HasMaxLength(10)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UpdTime)
                .IsRequired()
                .HasMaxLength(6)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UpdYmd)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.Zeiritsu).HasColumnType("numeric(3, 1)");
        }
    }
}
