// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using HassyaAllrightCloud.Domain.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace HassyaAllrightCloud.Infrastructure.Persistence
{
    public class TkdGridLyConfiguration : IEntityTypeConfiguration<TkdGridLy>
    {
        public void Configure(EntityTypeBuilder<TkdGridLy> entity)
        {
            entity.HasKey(e => new { e.SyainCdSeq, e.FormNm, e.GridNm, e.DspNo })
                .HasName("TKD_GridLy1");

            entity.ToTable("TKD_GridLy");

            entity.Property(e => e.FormNm)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.GridNm)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.ItemNm)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.UpdPrgId)
                .IsRequired()
                .HasColumnName("UpdPrgID")
                .HasMaxLength(10)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UpdTime)
                .IsRequired()
                .HasMaxLength(6)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UpdYmd)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();
        }
    }
}
