// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using HassyaAllrightCloud.Domain.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace HassyaAllrightCloud.Infrastructure.Persistence
{
    public class TkdKikyujConfiguration : IEntityTypeConfiguration<TkdKikyuj>
    {
        public void Configure(EntityTypeBuilder<TkdKikyuj> entity)
        {
            entity.HasKey(e => e.KinKyuTblCdSeq)
                .IsClustered(false);

            entity.ToTable("TKD_Kikyuj");

            entity.Property(e => e.BikoNm)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.KinKyuEtime)
                .IsRequired()
                .HasColumnName("KinKyuETime")
                .HasMaxLength(4)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.KinKyuEymd)
                .IsRequired()
                .HasColumnName("KinKyuEYmd")
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.KinKyuStime)
                .IsRequired()
                .HasColumnName("KinKyuSTime")
                .HasMaxLength(4)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.KinKyuSymd)
                .IsRequired()
                .HasColumnName("KinKyuSYmd")
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UpdPrgId)
                .IsRequired()
                .HasColumnName("UpdPrgID")
                .HasMaxLength(10)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UpdTime)
                .IsRequired()
                .HasMaxLength(6)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UpdYmd)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();
        }
    }
}
