// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using HassyaAllrightCloud.Domain.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace HassyaAllrightCloud.Infrastructure.Persistence
{
    public class TkdKuriConfiguration : IEntityTypeConfiguration<TkdKuri>
    {
        public void Configure(EntityTypeBuilder<TkdKuri> entity)
        {
            entity.HasKey(e => new { e.SeinKbn, e.YoyaKbn, e.SyoriYm, e.SyoEigyoSeq, e.SyoTokuiSeq, e.SyoSitenSeq, e.SeiFutSyu })
                .HasName("TKD_Kuri1");

            entity.ToTable("TKD_Kuri");

            entity.Property(e => e.SyoriYm)
                .HasMaxLength(6)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UpdPrgId)
                .IsRequired()
                .HasColumnName("UpdPrgID")
                .HasMaxLength(10)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UpdTime)
                .IsRequired()
                .HasMaxLength(6)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UpdYmd)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();
        }
    }
}
