// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using HassyaAllrightCloud.Domain.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace HassyaAllrightCloud.Infrastructure.Persistence
{
    public class TkdNotificationConfiguration : IEntityTypeConfiguration<TkdNotification>
    {
        public void Configure(EntityTypeBuilder<TkdNotification> entity)
        {
            entity.HasKey(e => e.ControlNo);

            entity.ToTable("TKD_Notification");

            entity.Property(e => e.ControlNo)
                .HasMaxLength(25)
                .IsFixedLength();

            entity.Property(e => e.SouSren).HasColumnName("SouSRen");

            entity.Property(e => e.SouStime)
                .IsRequired()
                .HasColumnName("SouSTime")
                .HasMaxLength(6)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.SouSymd)
                .IsRequired()
                .HasColumnName("SouSYmd")
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UpdPrgId)
                .IsRequired()
                .HasColumnName("UpdPrgID")
                .HasMaxLength(10)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UpdTime)
                .IsRequired()
                .HasMaxLength(6)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UpdYmd)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();
        }
    }
}
