// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using HassyaAllrightCloud.Domain.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace HassyaAllrightCloud.Infrastructure.Persistence
{
    public class TkdNyuSihConfiguration : IEntityTypeConfiguration<TkdNyuSih>
    {
        public void Configure(EntityTypeBuilder<TkdNyuSih> entity)
        {
            entity.HasKey(e => new { e.NyuSihTblSeq, e.TenantCdSeq })
                .HasName("TKD_NyuSih1");

            entity.ToTable("TKD_NyuSih");

            entity.Property(e => e.BankCd)
                .IsRequired()
                .HasMaxLength(4)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.BankSitCd)
                .IsRequired()
                .HasMaxLength(3)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.CardDen)
                .IsRequired()
                .HasMaxLength(15)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.CardSyo)
                .IsRequired()
                .HasMaxLength(23)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.EtcSyo1)
                .IsRequired()
                .HasMaxLength(23)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.EtcSyo2)
                .IsRequired()
                .HasMaxLength(15)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.NyuSihYmd)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.TegataNo)
                .IsRequired()
                .HasMaxLength(23)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.TegataYmd)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UpdPrgId)
                .IsRequired()
                .HasColumnName("UpdPrgID")
                .HasMaxLength(10)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UpdTime)
                .IsRequired()
                .HasMaxLength(6)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UpdYmd)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();
        }
    }
}
