// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using HassyaAllrightCloud.Domain.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace HassyaAllrightCloud.Infrastructure.Persistence
{
    public class TkdRyoPrSConfiguration : IEntityTypeConfiguration<TkdRyoPrS>
    {
        public void Configure(EntityTypeBuilder<TkdRyoPrS> entity)
        {
            entity.HasKey(e => e.RyoOutSeq);

            entity.ToTable("TKD_RyoPrS");

            entity.Property(e => e.RyoHatYmd)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.RyoOutTime)
                .IsRequired()
                .HasMaxLength(4)
                .IsFixedLength();

            entity.Property(e => e.UpdPrgId)
                .IsRequired()
                .HasColumnName("UpdPrgID")
                .HasMaxLength(10)
                .IsFixedLength();

            entity.Property(e => e.UpdTime)
                .IsRequired()
                .HasMaxLength(6)
                .IsFixedLength();

            entity.Property(e => e.UpdYmd)
                .IsRequired()
                .HasMaxLength(8)
                .IsFixedLength();
        }
    }
}
