// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using HassyaAllrightCloud.Domain.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace HassyaAllrightCloud.Infrastructure.Persistence
{
    public class TkdSeiPrSConfiguration : IEntityTypeConfiguration<TkdSeiPrS>
    {
        public void Configure(EntityTypeBuilder<TkdSeiPrS> entity)
        {
            entity.HasKey(e => new { e.SeiOutSeq, e.TenantCdSeq });

            entity.ToTable("TKD_SeiPrS");

            entity.Property(e => e.EndUkeNo)
                .IsRequired()
                .HasMaxLength(15)
                .IsFixedLength();

            entity.Property(e => e.Jyus1)
                .IsRequired()
                .HasMaxLength(60);

            entity.Property(e => e.Jyus2)
                .IsRequired()
                .HasMaxLength(60);

            entity.Property(e => e.SeiHatYmd)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.SeiOutTime)
                .IsRequired()
                .HasMaxLength(4)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.SeikYm)
                .IsRequired()
                .HasMaxLength(6)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.SitenNm)
                .IsRequired()
                .HasMaxLength(60);

            entity.Property(e => e.StaUkeNo)
                .IsRequired()
                .HasMaxLength(15)
                .IsFixedLength();

            entity.Property(e => e.TokuiNm)
                .IsRequired()
                .HasMaxLength(60);

            entity.Property(e => e.UpdPrgId)
                .IsRequired()
                .HasColumnName("UpdPrgID")
                .HasMaxLength(10)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UpdTime)
                .IsRequired()
                .HasMaxLength(6)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UpdYmd)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.ZipCd)
                .IsRequired()
                .HasMaxLength(12)
                .IsUnicode(false)
                .IsFixedLength();
        }
    }
}
