// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using HassyaAllrightCloud.Domain.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace HassyaAllrightCloud.Infrastructure.Persistence
{
    public class TkdShuYmdConfiguration : IEntityTypeConfiguration<TkdShuYmd>
    {
        public void Configure(EntityTypeBuilder<TkdShuYmd> entity)
        {
            entity.HasKey(e => new { e.ShuriTblSeq, e.ShuriYmd })
                .HasName("TKD_ShuYmd1");

            entity.ToTable("TKD_ShuYmd");

            entity.Property(e => e.ShuriYmd)
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.ShuriEtime)
                .IsRequired()
                .HasColumnName("ShuriETime")
                .HasMaxLength(4)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.ShuriStime)
                .IsRequired()
                .HasColumnName("ShuriSTime")
                .HasMaxLength(4)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UpdPrgId)
                .IsRequired()
                .HasColumnName("UpdPrgID")
                .HasMaxLength(10)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UpdTime)
                .IsRequired()
                .HasMaxLength(6)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UpdYmd)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();
        }
    }
}
