// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using HassyaAllrightCloud.Domain.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace HassyaAllrightCloud.Infrastructure.Persistence
{
    public class TkdSchYotKsyaFbConfiguration : IEntityTypeConfiguration<TkdSchYotKsyaFb>
    {
        public void Configure(EntityTypeBuilder<TkdSchYotKsyaFb> entity)
        {
            entity.HasKey(e => new { e.YoteiSeq, e.SyainCdSeq, e.YoteiSymd, e.YoteiStime });

            entity.ToTable("TKD_SchYotKSyaFb");

            entity.Property(e => e.YoteiSymd)
                .HasColumnName("YoteiSYmd")
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.YoteiStime)
                .HasColumnName("YoteiSTime")
                .HasMaxLength(6)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UpdPrgId)
                .IsRequired()
                .HasColumnName("UpdPrgID")
                .HasMaxLength(10)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UpdTime)
                .IsRequired()
                .HasMaxLength(6)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UpdYmd)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();
        }
    }
}
