// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using HassyaAllrightCloud.Domain.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace HassyaAllrightCloud.Infrastructure.Persistence
{
    public class TkdShabniConfiguration : IEntityTypeConfiguration<TkdShabni>
    {
        public void Configure(EntityTypeBuilder<TkdShabni> entity)
        {
            entity.HasKey(e => new { e.UkeNo, e.UnkRen, e.TeiDanNo, e.BunkRen, e.UnkYmd })
                .HasName("PK_TKD_Shabni_1");

            entity.ToTable("TKD_Shabni");

            entity.Property(e => e.UkeNo)
                .HasMaxLength(15)
                .IsFixedLength();

            entity.Property(e => e.UnkYmd)
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.EndMeter).HasColumnType("numeric(9, 2)");

            entity.Property(e => e.InspectionTime)
                .IsRequired()
                .HasMaxLength(4)
                .IsUnicode(false)
                .IsFixedLength()
                .HasDefaultValueSql("('0200')");

            entity.Property(e => e.JisTime)
                .IsRequired()
                .HasMaxLength(4)
                .IsUnicode(false)
                .IsFixedLength()
                .HasDefaultValueSql("('0000')");

            entity.Property(e => e.JisaIpkm)
                .HasColumnName("JisaIPKm")
                .HasColumnType("numeric(7, 2)");

            entity.Property(e => e.JisaKskm)
                .HasColumnName("JisaKSKm")
                .HasColumnType("numeric(7, 2)");

            entity.Property(e => e.KikTime)
                .IsRequired()
                .HasMaxLength(4)
                .IsUnicode(false)
                .IsFixedLength()
                .HasDefaultValueSql("('0000')");

            entity.Property(e => e.KisoIpkm)
                .HasColumnName("KisoIPkm")
                .HasColumnType("numeric(7, 2)");

            entity.Property(e => e.KisoKokm)
                .HasColumnName("KisoKOKm")
                .HasColumnType("numeric(7, 2)");

            entity.Property(e => e.KoskuTime)
                .IsRequired()
                .HasMaxLength(4)
                .IsUnicode(false)
                .IsFixedLength()
                .HasDefaultValueSql("('0000')");

            entity.Property(e => e.Nenryo1).HasColumnType("numeric(5, 2)");

            entity.Property(e => e.Nenryo2).HasColumnType("numeric(5, 2)");

            entity.Property(e => e.Nenryo3).HasColumnType("numeric(5, 2)");

            entity.Property(e => e.OthKm).HasColumnType("numeric(7, 2)");

            entity.Property(e => e.StMeter).HasColumnType("numeric(9, 2)");

            entity.Property(e => e.SyuKoTime)
                .IsRequired()
                .HasMaxLength(4)
                .IsUnicode(false)
                .IsFixedLength()
                .HasDefaultValueSql("('0000')");

            entity.Property(e => e.SyuPaTime)
                .IsRequired()
                .HasMaxLength(4)
                .IsUnicode(false)
                .IsFixedLength()
                .HasDefaultValueSql("('0000')");

            entity.Property(e => e.TouChTime)
                .IsRequired()
                .HasMaxLength(4)
                .IsUnicode(false)
                .IsFixedLength()
                .HasDefaultValueSql("('0000')");

            entity.Property(e => e.UnkKai).HasDefaultValueSql("((1))");

            entity.Property(e => e.UpdPrgId)
                .IsRequired()
                .HasColumnName("UpdPrgID")
                .HasMaxLength(10)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UpdTime)
                .IsRequired()
                .HasMaxLength(6)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UpdYmd)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.Zeiritsu).HasColumnType("numeric(3, 1)");
        }
    }
}
