// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using HassyaAllrightCloud.Domain.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace HassyaAllrightCloud.Infrastructure.Persistence
{
    public class TkdUnkobiFileConfiguration : IEntityTypeConfiguration<TkdUnkobiFile>
    {
        public void Configure(EntityTypeBuilder<TkdUnkobiFile> entity)
        {
            entity.HasKey(e => new { e.TenantCdSeq, e.UkeNo, e.UnkRen, e.FileNo })
                .HasName("TKD_UnkobiFile1");

            entity.ToTable("TKD_UnkobiFile");

            entity.Property(e => e.UkeNo)
                .HasMaxLength(15)
                .IsFixedLength();

            entity.Property(e => e.FileId)
                .IsRequired()
                .HasMaxLength(255)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.FolderId)
                .IsRequired()
                .HasMaxLength(255)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.UpdPrgId)
                .IsRequired()
                .HasColumnName("UpdPrgID")
                .HasMaxLength(10)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UpdTime)
                .IsRequired()
                .HasMaxLength(6)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UpdYmd)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();
        }
    }
}
