// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using HassyaAllrightCloud.Domain.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace HassyaAllrightCloud.Infrastructure.Persistence.Configurations
{
    public class TkdUnkobiConfiguration : IEntityTypeConfiguration<TkdUnkobi>
    {
        public void Configure(EntityTypeBuilder<TkdUnkobi> entity)
        {
            entity.HasKey(e => new { e.UkeNo, e.UnkRen })
                .IsClustered(false);

            entity.ToTable("TKD_Unkobi");

            entity.Property(e => e.UkeNo)
                .HasMaxLength(15)
                .IsFixedLength();

            entity.Property(e => e.AreaNm)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.BikoNm).HasMaxLength(250);

            entity.Property(e => e.CustomItems1)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.CustomItems10)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.CustomItems11)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.CustomItems12)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.CustomItems13)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.CustomItems14)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.CustomItems15)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.CustomItems16)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.CustomItems17)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.CustomItems18)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.CustomItems19)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.CustomItems2)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.CustomItems20)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.CustomItems3)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.CustomItems4)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.CustomItems5)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.CustomItems6)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.CustomItems7)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.CustomItems8)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.CustomItems9)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.DanTaKana)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.DanTaNm)
                .IsRequired()
                .HasMaxLength(100);

            entity.Property(e => e.DispKikTime)
                .HasMaxLength(4)
                .IsUnicode(false)
                .IsFixedLength()
                .HasComment("表示帰庫時間");

            entity.Property(e => e.DispKikYmd)
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength()
                .HasComment("表示帰庫日");

            entity.Property(e => e.DispSyuPaTime)
                .HasMaxLength(4)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.DispSyuPaYmd)
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.DispTouChTime)
                .HasMaxLength(4)
                .IsUnicode(false)
                .IsFixedLength()
                .HasComment("表示到着時間");

            entity.Property(e => e.DispTouYmd)
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength()
                .HasComment("表示到着年月日");

            entity.Property(e => e.GuiWnin).HasColumnName("GuiWNin");

            entity.Property(e => e.HaiIkbn).HasColumnName("HaiIKbn");

            entity.Property(e => e.HaiSbinCdSeq).HasColumnName("HaiSBinCdSeq");

            entity.Property(e => e.HaiSbinNm)
                .HasColumnName("HaiSBinNm")
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength()
                .HasComment("配車地便名");

            entity.Property(e => e.HaiScdSeq).HasColumnName("HaiSCdSeq");

            entity.Property(e => e.HaiSjyus1)
                .IsRequired()
                .HasColumnName("HaiSJyus1")
                .HasMaxLength(30);

            entity.Property(e => e.HaiSjyus2)
                .IsRequired()
                .HasColumnName("HaiSJyus2")
                .HasMaxLength(30);

            entity.Property(e => e.HaiSkbn).HasColumnName("HaiSKbn");

            entity.Property(e => e.HaiSkouKcdSeq).HasColumnName("HaiSKouKCdSeq");

            entity.Property(e => e.HaiSkouKnm)
                .HasColumnName("HaiSKouKNm")
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength()
                .HasComment("配車地交通機関名");

            entity.Property(e => e.HaiSnm)
                .IsRequired()
                .HasColumnName("HaiSNm")
                .HasMaxLength(50);

            entity.Property(e => e.HaiSsetTime)
                .IsRequired()
                .HasColumnName("HaiSSetTime")
                .HasMaxLength(4)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.HaiStime)
                .IsRequired()
                .HasColumnName("HaiSTime")
                .HasMaxLength(4)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.HaiSymd)
                .IsRequired()
                .HasColumnName("HaiSYmd")
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.HasNm)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.IkNm)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.KanDmhflg).HasColumnName("KanDMHFlg");

            entity.Property(e => e.KanJnm)
                .IsRequired()
                .HasColumnName("KanJNm")
                .HasMaxLength(20);

            entity.Property(e => e.KanjFax)
                .IsRequired()
                .HasMaxLength(14)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.KanjJyus1)
                .IsRequired()
                .HasMaxLength(30);

            entity.Property(e => e.KanjJyus2)
                .IsRequired()
                .HasMaxLength(30);

            entity.Property(e => e.KanjKeiNo)
                .IsRequired()
                .HasMaxLength(14)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.KanjMail)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.KanjTel)
                .IsRequired()
                .HasMaxLength(14)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.KhinKbn).HasColumnName("KHinKbn");

            entity.Property(e => e.KikTime)
                .IsRequired()
                .HasMaxLength(4)
                .IsUnicode(false)
                .IsFixedLength()
                .HasComment("帰庫時間");

            entity.Property(e => e.KikYmd)
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength()
                .HasComment("帰庫日");

            entity.Property(e => e.Kskbn).HasColumnName("KSKbn");

            entity.Property(e => e.OtherSystemCoperateCode)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.SyuKoTime)
                .IsRequired()
                .HasMaxLength(4)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.SyuPaTime)
                .IsRequired()
                .HasMaxLength(4)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.SyuPaYmd)
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength()
                .HasDefaultValueSql("('')");

            entity.Property(e => e.SyukoYmd)
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.TouChTime)
                .IsRequired()
                .HasMaxLength(4)
                .IsUnicode(false)
                .IsFixedLength()
                .HasComment("到着時間");

            entity.Property(e => e.TouJyusyo1)
                .IsRequired()
                .HasMaxLength(30);

            entity.Property(e => e.TouJyusyo2)
                .IsRequired()
                .HasMaxLength(30);

            entity.Property(e => e.TouKouKcdSeq).HasColumnName("TouKouKCdSeq");

            entity.Property(e => e.TouNm)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.TouSbinNm)
                .HasColumnName("TouSBinNm")
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength()
                .HasComment("到着地便名");

            entity.Property(e => e.TouSetTime)
                .IsRequired()
                .HasMaxLength(4)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.TouSkouKnm)
                .HasColumnName("TouSKouKNm")
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength()
                .HasComment("到着地交通機関名");

            entity.Property(e => e.TouYmd)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength()
                .HasComment("到着年月日");

            entity.Property(e => e.UnitPriceIndex).HasColumnType("numeric(3, 1)");

            entity.Property(e => e.UnkoJkbn).HasColumnName("UnkoJKbn");

            entity.Property(e => e.UnsoAllTim)
                .IsRequired()
                .HasMaxLength(5)
                .IsUnicode(false)
                .IsFixedLength()
                .HasDefaultValueSql("('')");

            entity.Property(e => e.UnsoJitTim)
                .IsRequired()
                .HasMaxLength(5)
                .IsUnicode(false)
                .IsFixedLength()
                .HasDefaultValueSql("('')");

            entity.Property(e => e.UnsoOutputYmd)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength()
                .HasDefaultValueSql("('')");

            entity.Property(e => e.UnsoShinSoTime)
                .IsRequired()
                .HasMaxLength(5)
                .IsUnicode(false)
                .IsFixedLength()
                .HasDefaultValueSql("('')");

            entity.Property(e => e.UnsoUnkEndTime)
                .IsRequired()
                .HasMaxLength(4)
                .IsUnicode(false)
                .IsFixedLength()
                .HasDefaultValueSql("('')");

            entity.Property(e => e.UnsoUnkStaTime)
                .IsRequired()
                .HasMaxLength(4)
                .IsUnicode(false)
                .IsFixedLength()
                .HasDefaultValueSql("('')");

            entity.Property(e => e.UpdPrgId)
                .IsRequired()
                .HasColumnName("UpdPrgID")
                .HasMaxLength(10)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UpdTime)
                .IsRequired()
                .HasMaxLength(6)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UpdYmd)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UriYmd)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();
        }
    }
}
