// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using HassyaAllrightCloud.Domain.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace HassyaAllrightCloud.Infrastructure.Persistence
{
    public class TkdYykshoConfiguration : IEntityTypeConfiguration<TkdYyksho>
    {
        public void Configure(EntityTypeBuilder<TkdYyksho> entity)
        {
            entity.HasKey(e => new { e.TenantCdSeq, e.UkeNo })
                .IsClustered(false);

            entity.ToTable("TKD_Yyksho");

            entity.Property(e => e.UkeNo)
                .HasMaxLength(15)
                .IsFixedLength()
                .HasComment("受付番号：[テナント3桁数][受付コード7桁数]");

            entity.Property(e => e.BikoNm).HasMaxLength(250);

            entity.Property(e => e.CanFuRiy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.CanFuYmd)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.CanRit).HasColumnType("numeric(4, 1)");

            entity.Property(e => e.CanRiy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.CanSyoR).HasColumnType("numeric(3, 1)");

            entity.Property(e => e.CanYmd)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.CanZkbn).HasColumnName("CanZKbn");

            entity.Property(e => e.FeeGuider)
                .HasColumnType("numeric(18, 0)")
                .HasComment("手数料税");

            entity.Property(e => e.FeeGuiderRate)
                .HasColumnType("numeric(3, 1)")
                .HasComment("手数料率（ガイド用）");

            entity.Property(e => e.GuiWnin).HasColumnName("GuiWNin");

            entity.Property(e => e.GuitKin).HasColumnType("numeric(18, 0)");

            entity.Property(e => e.HaiIkbn).HasColumnName("HaiIKbn");

            entity.Property(e => e.HaiSkbn).HasColumnName("HaiSKbn");

            entity.Property(e => e.KaktYmd)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.KhinKbn).HasColumnName("KHinKbn");

            entity.Property(e => e.Kskbn).HasColumnName("KSKbn");

            entity.Property(e => e.NcouKbn).HasColumnName("NCouKbn");

            entity.Property(e => e.ScouKbn).HasColumnName("SCouKbn");

            entity.Property(e => e.SeiTaiYmd)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.SeikYm)
                .IsRequired()
                .HasMaxLength(6)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.TaxGuider)
                .HasColumnType("numeric(18, 0)")
                .HasComment("ガイド税");

            entity.Property(e => e.TaxTypeforGuider)
                .HasDefaultValueSql("((3))")
                .HasComment("消費税タイプ（ガイド用）");

            entity.Property(e => e.TesuRitu).HasColumnType("numeric(3, 1)");

            entity.Property(e => e.TesuRyoG).HasColumnType("numeric(18, 0)");

            entity.Property(e => e.TokuiFax)
                .IsRequired()
                .HasMaxLength(14)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.TokuiMail)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.TokuiTanNm)
                .IsRequired()
                .HasMaxLength(16)
                .IsUnicode(false);

            entity.Property(e => e.TokuiTel)
                .IsRequired()
                .HasMaxLength(14)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.TourCd)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UkeCd).HasComment("受付コード");

            entity.Property(e => e.UkeYmd)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UntKin).HasColumnType("numeric(18, 0)");

            entity.Property(e => e.UpdPrgId)
                .IsRequired()
                .HasColumnName("UpdPrgID")
                .HasMaxLength(10)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UpdTime)
                .IsRequired()
                .HasMaxLength(6)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UpdYmd)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.YoyaKana)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.YoyaNm)
                .IsRequired()
                .HasMaxLength(100);

            entity.Property(e => e.ZeiRui).HasColumnType("numeric(18, 0)");

            entity.Property(e => e.Zeiritsu).HasColumnType("numeric(3, 1)");
        }
    }
}
