// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using HassyaAllrightCloud.Domain.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace HassyaAllrightCloud.Infrastructure.Persistence
{
    public class TkdYfutTuConfiguration : IEntityTypeConfiguration<TkdYfutTu>
    {
        public void Configure(EntityTypeBuilder<TkdYfutTu> entity)
        {
            entity.HasKey(e => new { e.UkeNo, e.UnkRen, e.YouTblSeq, e.FutTumKbn, e.YouFutTumRen })
                .HasName("TKD_YFutTu2")
                .IsClustered(false);

            entity.ToTable("TKD_YFutTu");

            entity.Property(e => e.UkeNo)
                .HasMaxLength(15)
                .IsFixedLength();

            entity.Property(e => e.DeRyoCd)
                .IsRequired()
                .HasMaxLength(3)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.DeRyoNm)
                .IsRequired()
                .HasMaxLength(10);

            entity.Property(e => e.FutTumNm)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.HasYmd)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.IriRyoCd)
                .IsRequired()
                .HasMaxLength(3)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.IriRyoNm)
                .IsRequired()
                .HasMaxLength(10);

            entity.Property(e => e.ScouKbn).HasColumnName("SCouKbn");

            entity.Property(e => e.SeisanNm)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.TesuRitu).HasColumnType("numeric(3, 1)");

            entity.Property(e => e.UpdPrgId)
                .IsRequired()
                .HasColumnName("UpdPrgID")
                .HasMaxLength(10)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UpdTime)
                .IsRequired()
                .HasMaxLength(6)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UpdYmd)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.Zeiritsu).HasColumnType("numeric(3, 1)");
        }
    }
}
