// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using HassyaAllrightCloud.Domain.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace HassyaAllrightCloud.Infrastructure.Persistence
{
    public class VpmAlertConfiguration : IEntityTypeConfiguration<VpmAlert>
    {
        public void Configure(EntityTypeBuilder<VpmAlert> entity)
        {
            entity.HasKey(e => e.AlertCdSeq);

            entity.ToView("VPM_Alert");

            entity.Property(e => e.AlertCdSeq).ValueGeneratedOnAdd();

            entity.Property(e => e.AlertContent).IsRequired();

            entity.Property(e => e.AlertNm)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.UpdPrgId)
                .IsRequired()
                .HasColumnName("UpdPrgID")
                .HasMaxLength(10)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UpdTime)
                .IsRequired()
                .HasMaxLength(6)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UpdYmd)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();
        }
    }
}
