// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using HassyaAllrightCloud.Domain.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace HassyaAllrightCloud.Infrastructure.Persistence
{
    public class VpmAlertSetConfiguration : IEntityTypeConfiguration<VpmAlertSet>
    {
        public void Configure(EntityTypeBuilder<VpmAlertSet> entity)
        {
            entity.HasKey(e => new { e.SyainCdSeq, e.AlertCd }).HasName("VpmAlertSet1");

            entity.ToView("VPM_AlertSet");
            entity.Property(e => e.SyainCdSeq).ValueGeneratedOnAdd();
            entity.Property(e => e.AlertCd).ValueGeneratedOnAdd();

            entity.Property(e => e.UpdPrgId)
                .IsRequired()
                .HasColumnName("UpdPrgID")
                .HasMaxLength(10)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UpdTime)
                .IsRequired()
                .HasMaxLength(6)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UpdYmd)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();
        }
    }
}
