// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using HassyaAllrightCloud.Domain.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace HassyaAllrightCloud.Infrastructure.Persistence
{
    public class VpmCompnyConfiguration : IEntityTypeConfiguration<VpmCompny>
    {
        public void Configure(EntityTypeBuilder<VpmCompny> entity)
        {
            entity.HasNoKey();

            entity.ToView("VPM_Compny");

            entity.Property(e => e.BusChatsuTesu)
                .HasColumnName("BusCHatsuTesu")
                .HasColumnType("numeric(6, 2)");

            entity.Property(e => e.BusChatsuTesuZei)
                .HasColumnName("BusCHatsuTesuZei")
                .HasColumnType("numeric(6, 2)");

            entity.Property(e => e.BusinessArea)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.BusinessPermitDate)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.BusinessPermitNumber)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.CompanyNm)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.RyakuNm)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);

            entity.Property(e => e.SeisanItakuRyo).HasColumnType("numeric(9, 0)");

            entity.Property(e => e.SyoriYm)
                .IsRequired()
                .HasMaxLength(6)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.TesuRitu).HasColumnType("numeric(3, 1)");

            entity.Property(e => e.UpdPrgId)
                .IsRequired()
                .HasColumnName("UpdPrgID")
                .HasMaxLength(10)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UpdTime)
                .IsRequired()
                .HasMaxLength(6)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UpdYmd)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.VoluntaryInsuranceHuman)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.VoluntaryInsuranceObject)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
        }
    }
}
