// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using HassyaAllrightCloud.Domain.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace HassyaAllrightCloud.Infrastructure.Persistence
{
    public class VpmHaichiConfiguration : IEntityTypeConfiguration<VpmHaichi>
    {
        public void Configure(EntityTypeBuilder<VpmHaichi> entity)
        {
            entity.HasNoKey();

            entity.ToView("VPM_Haichi");

            entity.Property(e => e.FaxNo)
                .IsRequired()
                .HasMaxLength(14)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.HaiScd)
                .IsRequired()
                .HasColumnName("HaiSCd")
                .HasMaxLength(5)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.HaiScdSeq)
                .HasColumnName("HaiSCdSeq");

            entity.Property(e => e.HaiSkigou)
                .IsRequired()
                .HasColumnName("HaiSKigou")
                .HasMaxLength(6)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.HaiSnm)
                .IsRequired()
                .HasColumnName("HaiSNm")
                .HasMaxLength(50);

            entity.Property(e => e.HaiStanNm)
                .IsRequired()
                .HasColumnName("HaiSTanNm")
                .HasMaxLength(20);

            entity.Property(e => e.Jyus1)
                .IsRequired()
                .HasMaxLength(30);

            entity.Property(e => e.Jyus2)
                .IsRequired()
                .HasMaxLength(30);

            entity.Property(e => e.RyakuNm)
                .IsRequired()
                .HasMaxLength(10);

            entity.Property(e => e.TelNo)
                .IsRequired()
                .HasMaxLength(14)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UpdPrgId)
                .IsRequired()
                .HasColumnName("UpdPrgID")
                .HasMaxLength(10)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UpdTime)
                .IsRequired()
                .HasMaxLength(6)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UpdYmd)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.ZipCd)
                .IsRequired()
                .HasMaxLength(12)
                .IsUnicode(false)
                .IsFixedLength();
        }
    }
}
