// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using HassyaAllrightCloud.Domain.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace HassyaAllrightCloud.Infrastructure.Persistence
{
    public class VpmKyoSetConfiguration : IEntityTypeConfiguration<VpmKyoSet>
    {
        public void Configure(EntityTypeBuilder<VpmKyoSet> entity)
        {
            entity.HasNoKey();

            entity.ToView("VPM_KyoSet");

            entity.Property(e => e.LogFd)
                .IsRequired()
                .HasMaxLength(200);

            entity.Property(e => e.LogFileNm)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.NyuSetcNm1)
                .IsRequired()
                .HasColumnName("NyuSEtcNm1")
                .HasMaxLength(10);

            entity.Property(e => e.NyuSetcNm2)
                .IsRequired()
                .HasColumnName("NyuSEtcNm2")
                .HasMaxLength(10);

            entity.Property(e => e.NyuSyoNm11)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.NyuSyoNm12)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.NyuSyoNm21)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.NyuSyoNm22)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.SetteiCd)
                .IsRequired()
                .HasMaxLength(3)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.SihSetcNm1)
                .IsRequired()
                .HasColumnName("SihSEtcNm1")
                .HasMaxLength(10);

            entity.Property(e => e.SihSetcNm2)
                .IsRequired()
                .HasColumnName("SihSEtcNm2")
                .HasMaxLength(10);

            entity.Property(e => e.SihSyoNm11)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.SihSyoNm12)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.SihSyoNm21)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.SihSyoNm22)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.SijJoKnm1)
                .IsRequired()
                .HasColumnName("SijJoKNm1")
                .HasMaxLength(10);

            entity.Property(e => e.SijJoKnm2)
                .IsRequired()
                .HasColumnName("SijJoKNm2")
                .HasMaxLength(10);

            entity.Property(e => e.SijJoKnm3)
                .IsRequired()
                .HasColumnName("SijJoKNm3")
                .HasMaxLength(10);

            entity.Property(e => e.SijJoKnm4)
                .IsRequired()
                .HasColumnName("SijJoKNm4")
                .HasMaxLength(10);

            entity.Property(e => e.SijJoKnm5)
                .IsRequired()
                .HasColumnName("SijJoKNm5")
                .HasMaxLength(10);

            entity.Property(e => e.TouKikTime)
                .IsRequired()
                .HasMaxLength(4)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.TouSyuKoTime)
                .IsRequired()
                .HasMaxLength(4)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UpdPrgId)
                .IsRequired()
                .HasColumnName("UpdPrgID")
                .HasMaxLength(10)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UpdTime)
                .IsRequired()
                .HasMaxLength(6)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UpdYmd)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.Zei1EndYmd)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.Zei1StaYmd)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.Zei2EndYmd)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.Zei2StaYmd)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.Zei3EndYmd)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.Zei3StaYmd)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.Zeiritsu1).HasColumnType("numeric(3, 1)");

            entity.Property(e => e.Zeiritsu2).HasColumnType("numeric(3, 1)");

            entity.Property(e => e.Zeiritsu3).HasColumnType("numeric(3, 1)");
        }
    }
}
