// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using HassyaAllrightCloud.Domain.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace HassyaAllrightCloud.Infrastructure.Persistence
{
    public class VpmKinKyuConfiguration : IEntityTypeConfiguration<VpmKinKyu>
    {
        public void Configure(EntityTypeBuilder<VpmKinKyu> entity)
        {
            entity.HasNoKey();

            entity.ToView("VPM_KinKyu");

            entity.Property(e => e.ColKinKyu)
                .IsRequired()
                .HasMaxLength(30);

            entity.Property(e => e.DefaultSyukinTime)
                .IsRequired()
                .HasMaxLength(4)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.DefaultTaiknTime)
                .IsRequired()
                .HasMaxLength(4)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.KinKyuCdSeq).ValueGeneratedOnAdd();

            entity.Property(e => e.KinKyuNm)
                .IsRequired()
                .HasMaxLength(20);

            entity.Property(e => e.KyuSyukinNm)
                .IsRequired()
                .HasMaxLength(20);

            entity.Property(e => e.KyuSyukinRyaku)
                .IsRequired()
                .HasMaxLength(10);

            entity.Property(e => e.RyakuNm)
                .IsRequired()
                .HasMaxLength(10);

            entity.Property(e => e.UpdPrgId)
                .IsRequired()
                .HasColumnName("UpdPrgID")
                .HasMaxLength(10)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UpdTime)
                .IsRequired()
                .HasMaxLength(6)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UpdYmd)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();
        }
    }
}
