// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using HassyaAllrightCloud.Domain.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace HassyaAllrightCloud.Infrastructure.Persistence
{
    public class VpmUserSetItmConfiguration : IEntityTypeConfiguration<VpmUserSetItm>
    {
        public void Configure(EntityTypeBuilder<VpmUserSetItm> entity)
        {
            entity.HasNoKey();

            entity.ToView("VPM_UserSetItm");

            entity.Property(e => e.DefaultVal)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.ItemCd)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.ItemNm)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.ItemSeq).ValueGeneratedOnAdd();

            entity.Property(e => e.ItemType)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.UpdPrgId)
                .IsRequired()
                .HasColumnName("UpdPrgID")
                .HasMaxLength(10)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UpdTime)
                .IsRequired()
                .HasMaxLength(6)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UpdYmd)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();
        }
    }
}
